#!/bin/bash
#PBS -l select=1:ncpus=1:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N all-0_beagle_windows
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/
for spp in bilineata flaviceps brunneicapillus sinuatus fusca nitens melanura crissale curvirostre bellii
do
echo $spp
window=0 ## alt = 0/1
	for i in *${spp}*beagle.gz; do 
	echo $i
		if [ "$window" -eq "0" ]; then
		echo "ZERO"
		zcat $i | awk 'FNR==1{header=$0; next} {match($1,".*_",tmp); chr=substr(tmp[0],1,length(tmp[0])-1); split($1,tmp,"_"); pos=tmp[length(tmp)]; file = chr"."int(pos/1000000000)".F.beagle"} outfile != file{outfile = file; print header > outfile} {print $0 > outfile}'
		else
		echo "ONE"
		zcat $i | awk 'FNR==1{header=$0; next} {match($1,".*_",tmp); chr=substr(tmp[0],1,length(tmp[0])-1); split($1,tmp,"_"); pos=tmp[length(tmp)]; file = chr"."int(pos/100000)".beagle"} outfile != file{outfile = file; print header > outfile} {print $0 > outfile}'
		fi
		rm NW*beagle*
		rm PseudoNW*beagle*
		rm SS*beagle*
		for tempbeag in PseudoNC*beagle*; do mv $tempbeag ${i}.${tempbeag}; done;
	done
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/

#mv *${spp}*beagle* $spp/
done