#!/bin/bash
#PBS -l select=1:ncpus=32:mem=64gb
#PBS -l walltime=5000:00:00
#PBS -N 19_Par_S1.Z.Fil_BWA_align
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

spp="Parrots"
logfile=${spp}_119_15_bwalog.txt

dofastqpair=0
dotrimming=0
dofastqc=0
dobwaalign=0 ## uses cores 
dosamtobam=0
doreadgroups=0
dodedup=0
dometrics=1

ref=/home/kprovost/nas3/genomeresequencingFromLucas/Melo_chrom/pseudochromosomesSHORT.fasta

cd /vz-nas1-active/RawGenomicReads/FASTQ_SCREEN_RESULTS/$spp

date
time

module load bwa-0.7.15
module load fastqc-0.11.5
module load R-3.4.1
#source activate stampy ## NEWLY ADDED from lucas

for i in *fq; do echo $i; gzip -f $i; done;
for i in *fastq; do echo $i; gzip -f $i; done;

#for i in */; do  
#	namei="${i///}" ## not there for lucas
#	cd $i; ## not there for lucas
for read1 in AMN_245113_P001_*_R1_combined.tagged_filter.fastq.gz; do 
name2=${read1%_R1_*} ## edited from lucas's
name=${name2#"RAPiD-Genomics_"}.$spp.zf.fil  ## edited from lucas's
read2=${read1%_R1_*}_R2_*.tagged_filter.fastq.gz  ## edited from lucas's		
header=`zcat $read1 | head -1`
IFS=':' read -a header <<< "$header"
INSTRUMENT=${header[0]}
RUN_ID=${header[1]}
FLOWCELL_BARCODE=${header[2]}
LANE=${header[3]}
ID=$FLOWCELL_BARCODE.$LANE
PU=$FLOWCELL_BARCODE.$LANE.$name
SM=$name
PL=ILLUMINA
LB=TrueSeq
echo $name $read1 $read2 $ID $PU $SM $PL $LB >> $logfile 2>&1 

echo ""  >> $logfile 2>&1 
echo "#######################"  >> $logfile 2>&1  
echo $name  >> $logfile 2>&1 
echo "#######################"  >> $logfile 2>&1  

##ADDED TO DEAL WITH THE MISMATCHED PAIRS 	
if [[ "$dofastqpair" -ne 0 ]]; then
	if [ ! -f "${read2%*.gz}.single.fq.gz" ]; then
		echo ""  >> $logfile 2>&1 
		echo ""  >> $logfile 2>&1 
		echo Separating unpaired >> $logfile 2>&1 
		echo ""  >> $logfile 2>&1 
		echo ""  >> $logfile 2>&1 
		echo "~~~unzip\n"
		gunzip -v $read1 >> $logfile 2>&1 
		gunzip -v $read2 >> $logfile 2>&1 
		echo "~~~pairs\n"
		/home/kprovost/nas3/fastq_pair ${read1%*.gz} ${read2%*.gz} >> $logfile 2>&1 
		echo "~~~zip\n"
		gzip -v ${read1%*.gz}.paired.fq >> $logfile 2>&1 
		gzip -v ${read1%*.gz}.single.fq >> $logfile 2>&1 
		gzip -v ${read1%*.gz} >> $logfile 2>&1 
		gzip -v ${read2%*.gz}.paired.fq >> $logfile 2>&1 
		gzip -v ${read2%*.gz}.single.fq >> $logfile 2>&1 
		gzip -v ${read2%*.gz} >> $logfile 2>&1 
	else
		echo "~~~Already done mismatching, skipping\n" >> $logfile 2>&1 
	fi 
fi

if [[ "$dotrimming" -ne 0 ]]; then
	if [ ! -f "$name.reverse_unpaired.fq.gz" ]; then
		echo >> $logfile 2>&1  
		echo >> $logfile 2>&1  
		echo Trimming adapters >> $logfile 2>&1  
		echo >> $logfile 2>&1   
		echo >> $logfile 2>&1  
		## edited from lucas's, his includes the raw_reads folder 
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/Trimmomatic-0.36/trimmomatic-0.36.jar \
		PE ${read1%*.gz}.paired.fq.gz ${read2%*.gz}.paired.fq.gz \
		$name.forward_paired.fq.gz \
		$name.forward_unpaired.fq.gz \
		$name.reverse_paired.fq.gz \
		$name.reverse_unpaired.fq.gz \
		ILLUMINACLIP:/home/kprovost/nas3/genomeresequencingFromLucas/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa:2:30:10:8:true \
		>> $logfile 2>&1  
		## FOR ABOVE: CHANGED #PE $read1 $read2 TO BE THE FIXED PAIRED ONE
	else 
		echo "~~~Already done trimming, skipping\n" >> $logfile 2>&1 
	fi
fi

echo >> $logfile 2>&1  
echo	 >> $logfile 2>&1 
echo Quality assessment >> $logfile 2>&1 
echo >> $logfile 2>&1 
echo >> $logfile 2>&1 

## edited from lucas's, his includes the raw_reads folder 
if [[ "$dofastqc" -ne 0 ]]; then
	time fastqc $name.forward_paired.fq.gz >> $logfile 2>&1 
	time fastqc $name.reverse_paired.fq.gz >> $logfile 2>&1 
fi

if [ ! -d "BAM_files/" ]; then 
	mkdir BAM_files 
fi ## added from lucas's 


if [[ "$dobwaalign" -ne 0 ]]; then
	if [ ! -f "BAM_files/$name.bam" ]; then
		echo >> $logfile 2>&1 
		echo	 >> $logfile 2>&1 
		echo Running BWA alignment >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		time bwa mem \
		-M \
		-t 28 \
		$ref \
		$name.forward_paired.fq.gz \
		$name.reverse_paired.fq.gz \
		> BAM_files/$name.sam ## added from lucas's 
		## CHECK IF THE SAM FILE IS BLANK 
		if [ -s "BAM_files/$name.sam" ]; then
			echo "BAM_files/$name.sam has some data."  >> $logfile 2>&1 
			check_sam=`~/nas3/samtools/samtools view BAM_files/$name.sam | head`
			if [ -z "$check_sam" ]; then
				echo "Error: THE SAM FILE HAS NO DATA"   >> $logfile 2>&1 
				echo "###################################################################"  >> $logfile 2>&1 
				break
			else
				echo "sam file has data. Moving on" >> $logfile 2>&1 
				# do something as file has data
			fi
		else
			echo "Error: BAM_files/$name.sam is empty. Removing it! \nEXITING"  >> $logfile 2>&1 
			rm BAM_files/$name.sam ## added from lucas's 
			echo "###################################################################"  >> $logfile 2>&1 
			break
		fi
	else
		echo "~~~Already done bam creation, skipping\n" >> $logfile 2>&1 
	fi 
fi

if [[ "$dosamtobam" -ne 0 ]]; then
	if [ ! -f "BAM_files/$name.bam" ]; then
		echo	 >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo Converting SAM to sorted BAM >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo	 >> $logfile 2>&1 
		## added the BAM_files folders 
		mkdir tmp
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar SortSam \
		INPUT=BAM_files/$name.sam \
		OUTPUT=BAM_files/$name.bam \
		SORT_ORDER=coordinate \
		TMP_DIR=`pwd`/tmp  >> $logfile 2>&1 
		rm -r tmp/
		rm BAM_files/$name.sam ## added from lucas's 
	else
		echo "~~~Already done bam creation, skipping\n" >> $logfile 2>&1 
	fi 
fi

## CHECK IF THE BAM FILE HAS INPUT AT ALL 

# this whole section added from lucas in case need to use STAMPY to do anything, but is commented out on his

## LUCAS'S PIPELINE HAS ADDING READ GROUP AND DEDUPLICATION BEFORE THIS POINT 

if [ ! -d "BAM_groupsAdded/" ]; then 
	mkdir BAM_groupsAdded
fi ## added from lucas's 

if [[ "$doreadgroups" -ne 0 ]]; then
	check_bam=`~/nas3/samtools/samtools view BAM_files/$name.bam | head`
	if [ -z "$check_bam" ]; then
		echo "Error: THE BAM FILE HAS NO DATA"   >> $logfile 2>&1 
		rm BAM_files/$name.bam
		echo "###################################################################"  >> $logfile 2>&1 
		#break
	else
		echo "Bam file has data. Moving on" >> $logfile 2>&1 
	fi

	if [ ! -f "BAM_groupsAdded/$name.groups_added.bam" ]; then
		echo >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo Adding Read Group >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		## added folders from Lucas 
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar AddOrReplaceReadGroups \
		I=BAM_files/$name.bam \
		O=BAM_groupsAdded/$name.groups_added.bam \
		RGID=$ID \
		RGLB=$LB \
		RGPL=$PL \
		RGPU=$PU \
		RGSM=$SM  >> $logfile 2>&1 
		#rm BAM_files/$name.bam
	else
		echo "~~~Already done adding groups, skipping\n" >> $logfile 2>&1 
	fi
fi


if [ ! -d "Stats/" ]; then 
	mkdir Stats
fi

if [ ! -d "BAM_dedup/" ]; then 
	mkdir BAM_dedup
fi ## added from lucas's 

if [[ "$dodedup" -ne 0 ]]; then
	if [ ! -f "BAM_dedup/$name.dedup.bam" ]; then 
		echo >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo Deduplication >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo >> $logfile 2>&1 

		## added folders from lucas 
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar MarkDuplicates \
		TMP_DIR=tmp \
		I=BAM_groupsAdded/$name.groups_added.bam \
		O=BAM_dedup/$name.dedup.bam \
		METRICS_FILE=Stats/$name.dedup.metrics.txt \
		REMOVE_DUPLICATES=false \
		MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1024 \
		TAGGING_POLICY=All  >> $logfile 2>&1 
		#rm -r tmp/
		#rm BAM_groupsAdded/$name.groups_added.bam
	else
		echo "~~~Already done deduplication, skipping\n" >> $logfile 2>&1 
	fi
fi

if [[ "$dometrics" -ne 0 ]]; then ## missing fi?
	if [ ! -f "Stats/$name.alignment_metrics.txt" ]; then 
		echo	 >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo Collecting alignment metrics >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		## add this from lucas's 
		## add folders to this 
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar CollectAlignmentSummaryMetrics \
		INPUT=BAM_files/$name.bam \
		OUTPUT=Stats/$name.alignment_metrics.txt \
		R=$ref \
		METRIC_ACCUMULATION_LEVEL=SAMPLE \
		METRIC_ACCUMULATION_LEVEL=READ_GROUP  >> $logfile 2>&1 
	else
		echo "~~~Already done alignment metrics, skipping\n" >> $logfile 2>&1 
	fi
	if [ ! -f "Stats/$name.insert_metrics.txt" ]; then 
		echo >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo Collect Insert Size Metrics >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		## add folders to this
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar CollectInsertSizeMetrics \
		INPUT=BAM_files/$name.bam \
		OUTPUT=Stats/$name.insert_metrics.txt \
		HISTOGRAM_FILE=Stats/$name.insert_size_histogram.pdf  >> $logfile 2>&1 
	else
		echo "~~~Already done insert metrics, skipping\n" >> $logfile 2>&1 
	fi
	if [ ! -f "Stats/$name.raw_wgs_metrics.txt" ]; then 
		echo >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo Collect Coverage Metrics >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		## add folders to this
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar CollectRawWgsMetrics \
		I=BAM_files/$name.bam \
		O=Stats/$name.raw_wgs_metrics.txt \
		R=$ref \
		INCLUDE_BQ_HISTOGRAM=true  >> $logfile 2>&1 

	else
		echo "~~~Already done WGS metrics, skipping\n" >> $logfile 2>&1 
	fi
	## AFTER THIS STEP LUCAS RUNS INDEXING AND QUALIMAP 
	if [ ! -f "BAM_dedup/$name.dedup.bai" ]; then 
		echo >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo Indexing BAM >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		echo >> $logfile 2>&1 
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar BuildBamIndex \
		I=BAM_dedup/$name.dedup.bam  >> $logfile 2>&1  ## folder added from lucas
	else
		echo "~~~Already done BAM index, skipping\n" >> $logfile 2>&1 
	fi
	echo >> $logfile 2>&1 
	echo >> $logfile 2>&1 
	echo Running QUALIMAP >> $logfile 2>&1 
	echo >> $logfile 2>&1 
	echo >> $logfile 2>&1 
	## copied from lucas 
	time qualimap bamqc -nt 8 -bam BAM_dedup/$name.dedup.bam -outdir Stats/$name.QUALIMAP --java-mem-size=8G   >> $logfile 2>&1 
	echo >> $logfile 2>&1 
	echo "#######################" >> $logfile 2>&1 
	echo "Moving finished files to ./DONE" >> $logfile 2>&1 
	echo "#######################" >> $logfile 2>&1 
	echo >> $logfile 2>&1 
	echo >> $logfile 2>&1 
fi

if [ ! -d "DONE/" ]; then 
	mkdir DONE
fi ## added from lucas's 

mv -nv $read1 ./DONE/
mv -nv $read2 ./DONE/

echo >> $logfile 2>&1 
echo "#######################" >> $logfile 2>&1 
echo $name DONE! >> $logfile 2>&1 
echo "#######################" >> $logfile 2>&1 
echo >> $logfile 2>&1 
echo >> $logfile 2>&1 

done

if [ ! -d "paired/" ]; then 
	mkdir paired
fi ## added from lucas's 

#mv *paired.* ./paired/  >> $logfile 2>&1 