#!/bin/bash
#PBS -l select=1:ncpus=32
#PBS -l walltime=5000:00:00
#PBS -N 1Par_PCAngsd
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## GL = genotype likehood file (Beagle format)
spp="Parrots"
mainpath="/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/${spp}/WINDOWS/"
source activate py36
#cd /home/kprovost/nas3/ANGSD_pipeline/pcangsd/pcangsd/
cd $mainpath

for GLu in ${mainpath}*.beagle; do
#echo $GLu
gzip -f $GLu
done;
 
for GL in ${mainpath}*LG2*beagle.gz; do
echo "###################"
echo $GL
outname=${GL%.beagle.gz}
echo $outname
for k in {1..1}; do
echo $k
if [ ! -f ${outname}.${spp}_PCAngsd.${k}*cov.npy* ]; then 
# Estimate covariance matrix and individual admixture proportions
echo "RUN"
date
time
python /home/kprovost/nas3/ANGSD_pipeline/pcangsd-0.98/pcangsd.py \
-beagle $GL \
-admix -admix_save -e $k \
-inbreed 2 \
-selection -sites_save \
-o ${outname}.${spp}_PCAngsd.$k \
-threads 32 > ${outname}.${spp}_pca.$k.log 2>&1
else
echo "ALREADY HERE1"
fi 
done
done

# for GLu in ./BEAGLE/${spp}/*F.beagle; do
# #echo $GLu
# gzip -f $GLu
# done;

# for GL in ./BEAGLE/${spp}/*.F.beagle.gz; do
# echo "###################"
# echo $GL
# outname=${GL%.beagle.gz}
# outname=${outname#./BEAGLE/$spp/}
# echo $outname
# for k in {1..4}; do
# echo $k
# if [ ! -f ./FOPTS/${outname}.${spp}_PCAngsd.${k}*qopt ]; then
# if [ ! -f ${outname}.${spp}_PCAngsd.${k}*qopt ]; then 
# # Estimate covariance matrix and individual admixture proportions
# echo "RUN"
# date
# time
# python2.7 /home/kprovost/nas3/pcangsd/pcangsd.py \
# -beagle $GL \
# -admix -admix_save -e $k \
# -inbreed 2 \
# -selection 1 -sites_save \
# -o ${outname}.${spp}_PCAngsd.$k \
#  -threads 32 > ${outname}.${spp}_pca.$k.log 2>&1
# else
# echo "ALREADY HERE1"
# fi 
# else
# echo "ALREADY HERE2"
# fi 
# mv *selection* ./SELECTIONS/
# mv *qopt* ./FOPTS/
# mv *fopt* ./FOPTS/
# mv *cov* ./COV_INBREED/
# mv *inbreed* ./COV_INBREED/
# mv *sites* ./PCASITES/
# mv *log* ./LOGS/
# done
# done
# 
# for GL in ./BEAGLE/${spp}/*.beagle.gz; do
# echo "###################"
# echo $GL
# outname=${GL%.beagle.gz}
# outname=${outname#./BEAGLE/$spp/}
# echo $outname
# for k in {1..4}; do
# echo $k
# if [ ! -f ./FOPTS/${outname}.${spp}_PCAngsd.${k}*qopt ]; then
# if [ ! -f ${outname}.${spp}_PCAngsd.${k}*qopt ]; then 
# # Estimate covariance matrix and individual admixture proportions
# echo "RUN"
# date
# time
# python2.7 /home/kprovost/nas3/pcangsd/pcangsd.py \
# -beagle $GL \
# -admix -admix_save -e $k \
# -inbreed 2 \
# -selection 1 -sites_save \
# -o ${outname}.${spp}_PCAngsd.$k \
#  -threads 32 > ${outname}.${spp}_pca.$k.log 2>&1
# else
# echo "ALREADY HERE1"
# fi 
# else
# echo "ALREADY HERE2"
# fi 
# mv *selection* ./SELECTIONS/
# mv *qopt* ./FOPTS/
# mv *fopt* ./FOPTS/
# mv *cov* ./COV_INBREED/
# mv *inbreed* ./COV_INBREED/
# mv *sites* ./PCASITES/
# mv *log* ./LOGS/
# done
# done