#!/bin/bash
#PBS -l select=2:ncpus=8
#PBS -l walltime=5000:00:00
#PBS -N S1S2_bru109_BWA_align
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zonotrichia_albicollis_GCF_000385455.1_Zonotrichia_albicollis-1.0.1_genomic.fna
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Strunus_vulgaris_GCF_001447265.1_Sturnus_vulgaris-1.0_genomic.fna


##References:
##Corvus -- Vireo bellii
##Parus -- Auriparus flaviceps
##Sturnus -- Toxostoma curvirostre, Toxostoma crissale, Campylorhynchus brunneicapillus, Polioptila melanura, Phainopepla nitens
##Zonotrichia -- Amphispiza brunneicapillus, Pipilo fuscus
##Geospiza -- Cardinalis cardinalis, Cardinalis sinuatus

cd /home/kprovost/nas3/AMN_245109/sequences/brunneicapillus/

date
time

module load bwa-0.7.15
module load fastqc-0.11.5
module load R-3.4.1

echo
echo
echo Merging BAM files
echo
echo

echo
echo "#######################"
echo "AMN_245109_P002_WE03_brunneicapillus.bam"
echo "#######################"

time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar MergeSamFiles \
I=AMN_245109_P002_WE03_brunneicapillus/F067_AMN_245109_P002_WE03_i5-515_i7-147_S103_L001.bam \
I=AMN_245109_P002_WE03_brunneicapillus/F069_AMN_245109_P002_WE03_i5-515_i7-147_S102_L001.bam \
I=AMN_245109_P002_WE03_brunneicapillus/F069_AMN_245109_P002_WE03_i5-515_i7-147_S102_L002.bam \
I=AMN_245109_P002_WE03_brunneicapillus/F069_AMN_245109_P002_WE03_i5-515_i7-147_S102_L003.bam \
I=AMN_245109_P002_WE03_brunneicapillus/F069_AMN_245109_P002_WE03_i5-515_i7-147_S102_L004.bam \
I=AMN_245109_P002_WE03_brunneicapillus/F069_AMN_245109_P002_WE03_i5-515_i7-147_S102_L005.bam \
O=AMN_245109_P002_WE03_brunneicapillus.bam

echo
echo "#######################"
echo "AMN_245109_P002_WE06_brunneicapillus.bam"
echo "#######################"


# time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar MergeSamFiles \
# I=AMN_245109_P002_WE06_brunneicapillus/F067_AMN_245109_P002_WE06_i5-515_i7-150_S105_L001.bam \
# I=AMN_245109_P002_WE06_brunneicapillus/F069_AMN_245109_P002_WE06_i5-515_i7-150_S104_L001.bam \
# I=AMN_245109_P002_WE06_brunneicapillus/F069_AMN_245109_P002_WE06_i5-515_i7-150_S104_L002.bam \
# I=AMN_245109_P002_WE06_brunneicapillus/F069_AMN_245109_P002_WE06_i5-515_i7-150_S104_L003.bam \
# I=AMN_245109_P002_WE06_brunneicapillus/F069_AMN_245109_P002_WE06_i5-515_i7-150_S104_L004.bam \
# I=AMN_245109_P002_WE06_brunneicapillus/F069_AMN_245109_P002_WE06_i5-515_i7-150_S104_L005.bam \
# O=AMN_245109_P002_WE06_brunneicapillus.bam

echo
echo "#######################"
echo "AMN_245109_P002_WF04_brunneicapillus.bam"
echo "#######################"


# time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar MergeSamFiles \
# I=AMN_245109_P002_WF04_brunneicapillus/F067_AMN_245109_P002_WF04_i5-515_i7-160_S109_L001.bam \
# I=AMN_245109_P002_WF04_brunneicapillus/F069_AMN_245109_P002_WF04_i5-515_i7-160_S108_L001.bam \
# I=AMN_245109_P002_WF04_brunneicapillus/F069_AMN_245109_P002_WF04_i5-515_i7-160_S108_L002.bam \
# I=AMN_245109_P002_WF04_brunneicapillus/F069_AMN_245109_P002_WF04_i5-515_i7-160_S108_L003.bam \
# I=AMN_245109_P002_WF04_brunneicapillus/F069_AMN_245109_P002_WF04_i5-515_i7-160_S108_L004.bam \
# I=AMN_245109_P002_WF04_brunneicapillus/F069_AMN_245109_P002_WF04_i5-515_i7-160_S108_L005.bam \
# O=AMN_245109_P002_WF04_brunneicapillus.bam

echo
echo "#######################"
echo DONE!
echo "#######################"
echo
echo