#!/bin/bash
#PBS -l select=1:ncpus=16
#PBS -l walltime=5000:00:00
#PBS -N bil109_S1.1_merge_bam
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

cd /vz-nas1-active/RawGenomicReads/AMN_245109/Plate2/bilineata/BAM_files
#cd /vz-nas1-active/RawGenomicReads/AMN_245111/Plate2/bilineata/BAM_files

prefix="F067" ## 109
#prefix="F073" ## 111
	
for bam in $prefix*L001.bam; do 
name=$(echo $bam | cut -d "_" -f 2-5); 

echo
echo "#######################"
echo $name
echo "#######################"

echo
echo
echo Merging Bam Files
echo
echo

command="time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar MergeSamFiles ";
for i in *$name*; do 
command="${command}I=${i} "; 
done; 
#echo $command;
merged="${name}_bilineata.bam"
command="${command} O=${merged}"
echo $command
eval $command
done;