#!/bin/bash
#PBS -l select=2:ncpus=14
#PBS -l walltime=5000:00:00
#PBS -N nit_val
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA04.merged.realigned.bam O=AMN_245111_P002_WA04.merged.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WC05.merged.realigned.bam O=AMN_245111_P002_WC05.merged.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WD05.merged.realigned.bam O=AMN_245111_P002_WD05.merged.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WE07.merged.realigned.bam O=AMN_245111_P002_WE07.merged.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WH03.merged.realigned.bam O=AMN_245111_P002_WH03.merged.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WA02_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WA02_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WB05_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WB05_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WB07_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WB07_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WC05_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WC05_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WC07_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WC07_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WD04_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WD04_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WD05_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WD05_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WD07_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WD07_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WE04_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WE04_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WE05_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WE05_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WE07_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WE07_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WG04_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WG04_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile I=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245112_P001_WH02_nitens.dedup.reheadered.clipped.realigned.bam O=AMN_245112_P001_WH02_nitens.dedup.reheadered.clipped.realigned.bam.validate.txt MODE=SUMMARY
