#!/bin/bash
#PBS -l select=1:ncpus=16
#PBS -l walltime=99999:00:00
#PBS -N mergeBam
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

## need a $name argument from qsub
## *realigned.bam

echo
echo "#######################"
echo $name
echo "#######################"

echo
echo
echo Merging Bam Files
echo
echo

command="time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar MarkDuplicates TMP_DIR=tmp "

for bam in *$name*.realigned.bam; 
do echo $bam; 
command="${command}I=${bam} "; 
done;

merged="${name}.merged.realigned.bam"
command="${command} O=${merged}"
command="${command} METRICS_FILE=$name.merged.realigned.metrics.txt REMOVE_DUPLICATES=false MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1024 TAGGING_POLICY=All"
echo
echo
echo "COMMAND IS:"
echo $command
echo
echo
eval $command
echo
echo