#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=99999:00:00
#PBS -N gzip
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
#cd $PBS_O_WORKDIR
#echo "pbsworkdir"
#echo $PBS_O_WORKDIR
#EXECDIR=`pwd`
#export PATH=./:$PATH
#echo $PATH

## arguments
## filename

for filename in /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/*/*bam; do
#echo $filename
gzip -f $filename
done 