#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=40:00:00
#PBS -N multisfs
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

module load R-3.6.3

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

Rscript /home/kprovost/nas3/multiSFS_to_meanSFS.R