cd "/Users/kprovost/Dropbox (AMNH)/Dissertation/CHAPTER2_GENOMES/CLUMPP_MacOSX.1.1.2"

#./CLUMPP -i SIN.K2.qopt.all.clumpp.txt -o SIN.K2.qopt.all.clumpp.txt.outfile -k 2 -c 25; mv data.miscfile SIN.K2.miscfile; mv data.perm_datafile SIN.K2.perm_datafile; sleep 0.5; 
#./CLUMPP -i SIN.K3.qopt.all.clumpp.txt -o SIN.K3.qopt.all.clumpp.txt.outfile -k 3 -c 25; mv data.miscfile SIN.K3.miscfile; mv data.perm_datafile SIN.K3.perm_datafile; sleep 0.5; 
#./CLUMPP -i SIN.K4.qopt.all.clumpp.txt -o SIN.K4.qopt.all.clumpp.txt.outfile -k 4 -c 25; mv data.miscfile SIN.K4.miscfile; mv data.perm_datafile SIN.K4.perm_datafile; sleep 0.5; 
#./CLUMPP -i SIN.K5.qopt.all.clumpp.txt -o SIN.K5.qopt.all.clumpp.txt.outfile -k 5 -c 25; mv data.miscfile SIN.K5.miscfile; mv data.perm_datafile SIN.K5.perm_datafile; sleep 0.5; 
# ./CLUMPP -i BIL.K2.qopt.all.clumpp.txt -o BIL.K2.qopt.all.clumpp.txt.outfile -k 2 -c 24 -r 35; mv data.miscfile BIL.K2.miscfile; mv data.perm_datafile BIL.K2.perm_datafile; sleep 0.5; 
# ./CLUMPP -i BIL.K3.qopt.all.clumpp.txt -o BIL.K3.qopt.all.clumpp.txt.outfile -k 3 -c 24 -r 35; mv data.miscfile BIL.K3.miscfile; mv data.perm_datafile BIL.K3.perm_datafile; sleep 0.5; 
# ./CLUMPP -i BIL.K4.qopt.all.clumpp.txt -o BIL.K4.qopt.all.clumpp.txt.outfile -k 4 -c 24 -r 35; mv data.miscfile BIL.K4.miscfile; mv data.perm_datafile BIL.K4.perm_datafile; sleep 0.5; 
# ./CLUMPP -i BIL.K5.qopt.all.clumpp.txt -o BIL.K5.qopt.all.clumpp.txt.outfile -k 5 -c 24 -r 35; mv data.miscfile BIL.K5.miscfile; mv data.perm_datafile BIL.K5.perm_datafile; sleep 0.5; 
# ./CLUMPP -i BRU.K2.qopt.all.clumpp.txt -o BRU.K2.qopt.all.clumpp.txt.outfile -k 2 -c 22 -r 34; mv data.miscfile BRU.K2.miscfile; mv data.perm_datafile BRU.K2.perm_datafile; sleep 0.5; 
# ./CLUMPP -i BRU.K3.qopt.all.clumpp.txt -o BRU.K3.qopt.all.clumpp.txt.outfile -k 3 -c 22 -r 34; mv data.miscfile BRU.K3.miscfile; mv data.perm_datafile BRU.K3.perm_datafile; sleep 0.5; 
# ./CLUMPP -i BRU.K4.qopt.all.clumpp.txt -o BRU.K4.qopt.all.clumpp.txt.outfile -k 4 -c 22 -r 34; mv data.miscfile BRU.K4.miscfile; mv data.perm_datafile BRU.K4.perm_datafile; sleep 0.5; 
# ./CLUMPP -i BRU.K5.qopt.all.clumpp.txt -o BRU.K5.qopt.all.clumpp.txt.outfile -k 5 -c 22 -r 34; mv data.miscfile BRU.K5.miscfile; mv data.perm_datafile BRU.K5.perm_datafile; sleep 0.5; 
# ./CLUMPP -i CRI.K2.qopt.all.clumpp.txt -o CRI.K2.qopt.all.clumpp.txt.outfile -k 2 -c 22 -r 34; mv data.miscfile CRI.K2.miscfile; mv data.perm_datafile CRI.K2.perm_datafile; sleep 0.5; 
# ./CLUMPP -i CRI.K3.qopt.all.clumpp.txt -o CRI.K3.qopt.all.clumpp.txt.outfile -k 3 -c 22 -r 34; mv data.miscfile CRI.K3.miscfile; mv data.perm_datafile CRI.K3.perm_datafile; sleep 0.5; 
# ./CLUMPP -i CRI.K4.qopt.all.clumpp.txt -o CRI.K4.qopt.all.clumpp.txt.outfile -k 4 -c 22 -r 34; mv data.miscfile CRI.K4.miscfile; mv data.perm_datafile CRI.K4.perm_datafile; sleep 0.5; 
# ./CLUMPP -i CRI.K5.qopt.all.clumpp.txt -o CRI.K5.qopt.all.clumpp.txt.outfile -k 5 -c 22 -r 34; mv data.miscfile CRI.K5.miscfile; mv data.perm_datafile CRI.K5.perm_datafile; sleep 0.5; 
# ./CLUMPP -i CUR.K2.qopt.all.clumpp.txt -o CUR.K2.qopt.all.clumpp.txt.outfile -k 2 -c 21 -r 34; mv data.miscfile CUR.K2.miscfile; mv data.perm_datafile CUR.K2.perm_datafile; sleep 0.5; 
# ./CLUMPP -i CUR.K3.qopt.all.clumpp.txt -o CUR.K3.qopt.all.clumpp.txt.outfile -k 3 -c 21 -r 34; mv data.miscfile CUR.K3.miscfile; mv data.perm_datafile CUR.K3.perm_datafile; sleep 0.5; 
# ./CLUMPP -i CUR.K4.qopt.all.clumpp.txt -o CUR.K4.qopt.all.clumpp.txt.outfile -k 4 -c 21 -r 34; mv data.miscfile CUR.K4.miscfile; mv data.perm_datafile CUR.K4.perm_datafile; sleep 0.5; 
# ./CLUMPP -i CUR.K5.qopt.all.clumpp.txt -o CUR.K5.qopt.all.clumpp.txt.outfile -k 5 -c 21 -r 34; mv data.miscfile CUR.K5.miscfile; mv data.perm_datafile CUR.K5.perm_datafile; sleep 0.5; 
# ./CLUMPP -i FUS.K2.qopt.all.clumpp.txt -o FUS.K2.qopt.all.clumpp.txt.outfile -k 2 -c 24 -r 35; mv data.miscfile FUS.K2.miscfile; mv data.perm_datafile FUS.K2.perm_datafile; sleep 0.5; 
# ./CLUMPP -i FUS.K3.qopt.all.clumpp.txt -o FUS.K3.qopt.all.clumpp.txt.outfile -k 3 -c 24 -r 35; mv data.miscfile FUS.K3.miscfile; mv data.perm_datafile FUS.K3.perm_datafile; sleep 0.5; 
# ./CLUMPP -i FUS.K4.qopt.all.clumpp.txt -o FUS.K4.qopt.all.clumpp.txt.outfile -k 4 -c 24 -r 35; mv data.miscfile FUS.K4.miscfile; mv data.perm_datafile FUS.K4.perm_datafile; sleep 0.5; 
# ./CLUMPP -i FUS.K5.qopt.all.clumpp.txt -o FUS.K5.qopt.all.clumpp.txt.outfile -k 5 -c 24 -r 35; mv data.miscfile FUS.K5.miscfile; mv data.perm_datafile FUS.K5.perm_datafile; sleep 0.5; 
# ./CLUMPP -i MEL.K2.qopt.all.clumpp.txt -o MEL.K2.qopt.all.clumpp.txt.outfile -k 2 -c 23 -r 34; mv data.miscfile MEL.K2.miscfile; mv data.perm_datafile MEL.K2.perm_datafile; sleep 0.5; 
# ./CLUMPP -i MEL.K3.qopt.all.clumpp.txt -o MEL.K3.qopt.all.clumpp.txt.outfile -k 3 -c 23 -r 34; mv data.miscfile MEL.K3.miscfile; mv data.perm_datafile MEL.K3.perm_datafile; sleep 0.5; 
# ./CLUMPP -i MEL.K4.qopt.all.clumpp.txt -o MEL.K4.qopt.all.clumpp.txt.outfile -k 4 -c 23 -r 34; mv data.miscfile MEL.K4.miscfile; mv data.perm_datafile MEL.K4.perm_datafile; sleep 0.5; 
# ./CLUMPP -i MEL.K5.qopt.all.clumpp.txt -o MEL.K5.qopt.all.clumpp.txt.outfile -k 5 -c 23 -r 34; mv data.miscfile MEL.K5.miscfile; mv data.perm_datafile MEL.K5.perm_datafile; sleep 0.5; 
# ./CLUMPP -i NIT.K2.qopt.all.clumpp.txt -o NIT.K2.qopt.all.clumpp.txt.outfile -k 2 -c 20 -r 34; mv data.miscfile NIT.K2.miscfile; mv data.perm_datafile NIT.K2.perm_datafile; sleep 0.5; 
# ./CLUMPP -i NIT.K3.qopt.all.clumpp.txt -o NIT.K3.qopt.all.clumpp.txt.outfile -k 3 -c 20 -r 34; mv data.miscfile NIT.K3.miscfile; mv data.perm_datafile NIT.K3.perm_datafile; sleep 0.5; 
# ./CLUMPP -i NIT.K4.qopt.all.clumpp.txt -o NIT.K4.qopt.all.clumpp.txt.outfile -k 4 -c 20 -r 34; mv data.miscfile NIT.K4.miscfile; mv data.perm_datafile NIT.K4.perm_datafile; sleep 0.5; 
# ./CLUMPP -i NIT.K5.qopt.all.clumpp.txt -o NIT.K5.qopt.all.clumpp.txt.outfile -k 5 -c 20 -r 34; mv data.miscfile NIT.K5.miscfile; mv data.perm_datafile NIT.K5.perm_datafile; sleep 0.5; 
#./CLUMPP -i BEL.K2.qopt.all.clumpp.txt -o BEL.K2.qopt.all.clumpp.txt.outfile -k 2 -c 18; mv data.miscfile BEL.K2.miscfile; mv data.perm_datafile BEL.K2.perm_datafile; sleep 0.5; 
#./CLUMPP -i BEL.K3.qopt.all.clumpp.txt -o BEL.K3.qopt.all.clumpp.txt.outfile -k 3 -c 18; mv data.miscfile BEL.K3.miscfile; mv data.perm_datafile BEL.K3.perm_datafile; sleep 0.5; 
#./CLUMPP -i BEL.K4.qopt.all.clumpp.txt -o BEL.K4.qopt.all.clumpp.txt.outfile -k 4 -c 18; mv data.miscfile BEL.K4.miscfile; mv data.perm_datafile BEL.K4.perm_datafile; sleep 0.5; 
#./CLUMPP -i BEL.K5.qopt.all.clumpp.txt -o BEL.K5.qopt.all.clumpp.txt.outfile -k 5 -c 18; mv data.miscfile BEL.K5.miscfile; mv data.perm_datafile BEL.K5.perm_datafile; sleep 0.5; 
#./CLUMPP -i FLA.K2.qopt.all.clumpp.txt -o FLA.K2.qopt.all.clumpp.txt.outfile -k 2 -c 22; mv data.miscfile FLA.K2.miscfile; mv data.perm_datafile FLA.K2.perm_datafile; sleep 0.5; 
#./CLUMPP -i FLA.K3.qopt.all.clumpp.txt -o FLA.K3.qopt.all.clumpp.txt.outfile -k 3 -c 22; mv data.miscfile FLA.K3.miscfile; mv data.perm_datafile FLA.K3.perm_datafile; sleep 0.5; 
#./CLUMPP -i FLA.K4.qopt.all.clumpp.txt -o FLA.K4.qopt.all.clumpp.txt.outfile -k 4 -c 22; mv data.miscfile FLA.K4.miscfile; mv data.perm_datafile FLA.K4.perm_datafile; sleep 0.5; 
#./CLUMPP -i FLA.K5.qopt.all.clumpp.txt -o FLA.K5.qopt.all.clumpp.txt.outfile -k 5 -c 24 -r 35; mv data.miscfile FLA.K5.miscfile; mv data.perm_datafile FLA.K5.perm_datafile; sleep 0.5; 
