#!/bin/bash
#PBS -l select=1:ncpus=16
#PBS -l walltime=5000:00:00
#PBS -N Stairwayplot2
#PBS -j oe
#PBS -m ae
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

cd "/home/kprovost/nas3/STAIRWAYPLOT"

blueprint="curvirostre_son_50.blueprint"

java -cp /home/lmoreira/Picoides_pubescens/SNP_calling_from_pseudochrom/stairway2/stairway_plot_v2.1.1/stairway_plot_es Stairbuilder $blueprint

bash $blueprint.sh

