#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=5000:00:00
#PBS -N GATKsnpFilter2fusca
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
## vcf=vcf file
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zonotrichia_albicollis_GCF_000385455.1_Zonotrichia_albicollis-1.0.1_genomic.fna
vcf=/home/kprovost/nas3/AMN_245107/sequences/fusca/fusca.allsamples.recal.raw.vcf

cd /home/kprovost/nas3/AMN_245107/sequences/fusca/

echo
echo "#######################"
echo $vcf
echo "#######################"

echo
echo
echo Filtering SNPs
echo
echo

time /home/kprovost/nas3/genomeresequencingFromLucas/gatk-4.0.5.1/gatk VariantFiltration \
-R $ref \
-V $vcf \
--filter-expression "!vc.hasAttribute('DP')" \
--filter-name "noCoverage" \
--filter-expression "(vc.isSNP() && (vc.hasAttribute('ReadPosRankSum') && ReadPosRankSum < -8.0)) || ((vc.isIndel() || vc.isMixed()) && (vc.hasAttribute('ReadPosRankSum') && ReadPosRankSum < -20.0)) || (vc.hasAttribute('QD') && QD < 2.0) " \
--filter-name "badSeq" \
--filter-expression "(vc.isSNP() && ((vc.hasAttribute('FS') && FS > 60.0) || (vc.hasAttribute('SOR') &&  SOR > 3.0))) || ((vc.isIndel() || vc.isMixed()) && ((vc.hasAttribute('FS') && FS > 200.0) || (vc.hasAttribute('SOR') &&  SOR > 10.0)))" \
--filter-name "badStrand" \
--filter-expression "vc.isSNP() && ((vc.hasAttribute('MQ') && MQ < 40.0) || (vc.hasAttribute('MQRankSum') && MQRankSum < -12.5))" \
--filter-name "badMap" \
-O fusca.allsamples_filtered.vcf \
