#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=5000:00:00
#PBS -N bru109_8_GATKsnpFilter2
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
## vcf=vcf file
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zonotrichia_albicollis_GCF_000385455.1_Zonotrichia_albicollis-1.0.1_genomic.fna
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Strunus_vulgaris_GCF_001447265.1_Sturnus_vulgaris-1.0_genomic.fna
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Geospiza_fortis_GCF_000277835.1_GeoFor_1.0_genomic.fna 
##References:
##Corvus -- Vireo
##Parus -- Auriparus
##Sturnus -- Toxostoma Campylorhynchus
		  ## Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo/Melozone
##Geospiza -- Cardinalis

vcf=/home/kprovost/nas3/EVERY_PLATE/dedup_bam/brunneicapillus/brunneicapillus_batch2.allsamples.recal.raw.vcf

cd /home/kprovost/nas3/EVERY_PLATE/dedup_bam/brunneicapillus

echo
echo "#######################"
echo $vcf
echo "#######################"

echo
echo
echo Filtering SNPs
echo
echo

time /home/kprovost/nas3/genomeresequencingFromLucas/gatk-4.0.5.1/gatk VariantFiltration \
-R $ref \
-V $vcf \
--filter-expression "!vc.hasAttribute('DP')" \
--filter-name "noCoverage" \
--filter-expression "(vc.isSNP() && (vc.hasAttribute('ReadPosRankSum') && ReadPosRankSum < -8.0)) || ((vc.isIndel() || vc.isMixed()) && (vc.hasAttribute('ReadPosRankSum') && ReadPosRankSum < -20.0)) || (vc.hasAttribute('QD') && QD < 2.0) " \
--filter-name "badSeq" \
--filter-expression "(vc.isSNP() && ((vc.hasAttribute('FS') && FS > 60.0) || (vc.hasAttribute('SOR') &&  SOR > 3.0))) || ((vc.isIndel() || vc.isMixed()) && ((vc.hasAttribute('FS') && FS > 200.0) || (vc.hasAttribute('SOR') &&  SOR > 10.0)))" \
--filter-name "badStrand" \
--filter-expression "vc.isSNP() && ((vc.hasAttribute('MQ') && MQ < 40.0) || (vc.hasAttribute('MQRankSum') && MQRankSum < -12.5))" \
--filter-name "badMap" \
-O brunneicapillus_batch2.allsamples_filtered.vcf \
