#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=5000:00:00
#PBS -N bru109_5_GATKSNPfilter
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zonotrichia_albicollis_GCF_000385455.1_Zonotrichia_albicollis-1.0.1_genomic.fna
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Strunus_vulgaris_GCF_001447265.1_Sturnus_vulgaris-1.0_genomic.fna
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Geospiza_fortis_GCF_000277835.1_GeoFor_1.0_genomic.fna 
##References:
##Corvus -- Vireo
##Parus -- Auriparus
##Sturnus -- Toxostoma Campylorhynchus
		  ## Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo/Melozone
##Geospiza -- Cardinalis

## vcf=allsamples.raw.vcf
vcf=/home/kprovost/nas3/EVERY_PLATE/brunneicapillus/allsamples_batch2_brunneicapillus.raw.vcf 

cd /home/kprovost/nas3/EVERY_PLATE/brunneicapillus


echo
echo "#######################"
echo $vcf
echo "#######################"

echo
echo
echo Filtering SNPs
echo
echo

time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar -T VariantFiltration \
-R $ref \
-V $vcf \
--filterExpression "!vc.hasAttribute('DP')" \
--filterName "noCoverage" \
--filterExpression "vc.hasAttribute('DP') && DP < 2" \
--filterName "MinCov" \
--filterExpression "vc.hasAttribute('DP') && DP > 10" \
--filterName "MaxCov" \
--filterExpression "(vc.isSNP() && (vc.hasAttribute('ReadPosRankSum') && ReadPosRankSum < -8.0)) || ((vc.isIndel() || vc.isMixed()) && (vc.hasAttribute('ReadPosRankSum') && ReadPosRankSum < -20.0)) || (vc.hasAttribute('QD') && QD < 2.0) " \
--filterName "badSeq" \
--filterExpression "(vc.isSNP() && ((vc.hasAttribute('FS') && FS > 60.0) || (vc.hasAttribute('SOR') &&  SOR > 3.0))) || ((vc.isIndel() || vc.isMixed()) && ((vc.hasAttribute('FS') && FS > 200.0) || (vc.hasAttribute('SOR') &&  SOR > 10.0)))" \
--filterName "badStrand" \
--filterExpression "vc.isSNP() && ((vc.hasAttribute('MQ') && MQ < 40.0) || (vc.hasAttribute('MQRankSum') && MQRankSum < -12.5))" \
--filterName "badMap" \
-o brunneicapillus_batch2.combined.db.vcf
