#!/bin/bash
#PBS -l select=1:ncpus=16
#PBS -l walltime=5000:00:00
#PBS -N S11_allmiss_GATKsnpSelVARS
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## vcf

vcf=/vz-nas1-active/RawGenomicReads/FASTQ_SCREEN_RESULTS/Parrots/BAM_dedup/parrots.recal_filtered.vcf

cd /vz-nas1-active/RawGenomicReads/FASTQ_SCREEN_RESULTS/Parrots/BAM_dedup


echo
echo "#######################"
echo $vcf
echo "#######################"

echo
echo
echo Selecting Variants
echo
echo

## didn't change
/home/kprovost/opt/bin/vcftools \
--vcf $vcf \
--remove-indels \
--remove-filtered-all \
--min-meanDP 2 \
--max-meanDP 10 \
--max-maf 0.05 \
--max-missing 0 \
--hwe 0.01 \
--min-alleles 2 \
--max-alleles 2 \
--recode \
--recode-INFO-all \
--out parrots.recal_filtered-SNP-only_alldata