#!/bin/bash
#PBS -l select=1:ncpus=64
#PBS -l walltime=5000:00:00
#PBS -N GATKsnpGVCFbru
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Strunus_vulgaris_GCF_001447265.1_Sturnus_vulgaris-1.0_genomic.fna

cd /home/kprovost/nas3/AMN_245107/sequences/brunneicapillus/brunneicapillus_raw_vcf


echo
echo
echo Combine GVCFs
echo
echo

time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar \
-T GenotypeGVCFs \
-R $ref \
--variant AMN_245107_P01_WA02_brunneicapillus.raw.g.vcf \
--variant AMN_245107_P01_WB02_brunneicapillus.raw.g.vcf \
--variant AMN_245107_P01_WF01_brunneicapillus.raw.g.vcf \
--variant AMN_245107_P01_WG01_brunneicapillus.raw.g.vcf \
--variant AMN_245107_P01_WH01_brunneicapillus.raw.g.vcf \
-o allsamples_brunneicapillus.raw.vcf \
-nt 64
##### nt not there originally, didn't have slash before