#!/bin/bash
#PBS -l select=2:ncpus=64
#PBS -l walltime=5000:00:00
#PBS -N S1S2_BWA_align_bil109
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zonotrichia_albicollis_GCF_000385455.1_Zonotrichia_albicollis-1.0.1_genomic.fna

##References:
##Corvus -- Vireo bellii
##Parus -- Auriparus flaviceps
##Sturnus -- Toxostoma curvirostre, Toxostoma crissale, Campylorhynchus brunneicapillus, Polioptila melanura, Phainopepla nitens
##Zonotrichia -- Amphispiza bilineata, Pipilo fuscus
##Geospiza -- Cardinalis cardinalis, Cardinalis sinuatus

cd /home/kprovost/nas3/AMN_245109/sequences/bilineata/

date
time

module load bwa-0.7.15
module load fastqc-0.11.5
module load R-3.4.1

for i in */; do  
	namei="${i///}"
	cd $i; 
	for read1 in RAPiD-Genomics_*_R1_*; do 
		name2=${read1%_R1_*}
		name=${name2#"RAPiD-Genomics_"}
		read2=${read1%_R1_*}_R2_*		
		header=`zcat $read1 | head -1`
		IFS=':' read -a header <<< "$header"
		INSTRUMENT=${header[0]}
		RUN_ID=${header[1]}
		FLOWCELL_BARCODE=${header[2]}
		LANE=${header[3]}
		ID=$FLOWCELL_BARCODE.$LANE
		PU=$FLOWCELL_BARCODE.$LANE.$name
		SM=$name
		PL=ILLUMINA
		LB=TrueSeq
		echo $name $read1 $read2 $ID $PU $SM $PL $LB
	
		echo
		echo "#######################"
		echo $name
		echo "#######################"

		echo
		echo
		echo Trimming adapters
		echo
		echo

		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/Trimmomatic-0.36/trimmomatic-0.36.jar \
		PE $read1 $read2 \
		$name.forward_paired.fq.gz \
		$name.forward_unpaired.fq.gz \
		$name.reverse_paired.fq.gz \
		$name.reverse_unpaired.fq.gz \
		ILLUMINACLIP:/home/kprovost/nas3/genomeresequencingFromLucas/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa:2:30:10:8:true

		echo
		echo	
		echo Quality assessment
		echo
		echo

		time fastqc $name.forward_paired.fq.gz
		time fastqc $name.reverse_paired.fq.gz

		echo
		echo	
		echo Running BWA alignment
		echo
		echo
	
		time bwa mem \
		-M \
		-t 28 \
		$ref \
		$name.forward_paired.fq.gz \
		$name.reverse_paired.fq.gz \
		> $name.sam

		echo	
		echo
		echo Converting SAM to sorted BAM
		echo
		echo	
	
		mkdir tmp
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar SortSam \
		INPUT=$name.sam \
		OUTPUT=$name.bam \
		SORT_ORDER=coordinate \
		TMP_DIR=`pwd`/tmp
		rm -r tmp/

		echo	
		echo
		echo Collecting alignment metrics
		echo
		echo
	
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar CollectAlignmentSummaryMetrics \
		INPUT=$name.bam \
		OUTPUT=$name.alignment_metrics.txt \
		R=$ref \
		METRIC_ACCUMULATION_LEVEL=SAMPLE \
		METRIC_ACCUMULATION_LEVEL=READ_GROUP \

		echo
		echo
		echo Collect Insert Size Metrics
		echo
		echo
	
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar CollectInsertSizeMetrics \
		INPUT=$name.bam \
		OUTPUT=$name.insert_metrics.txt \
		HISTOGRAM_FILE=$name.insert_size_histogram.pdf

		echo
		echo
		echo Collect Coverage Metrics
		echo
		echo

		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar CollectRawWgsMetrics \
		I=$name.bam \
		O=$name.raw_wgs_metrics.txt \
		R=$ref \
		INCLUDE_BQ_HISTOGRAM=true
	
		#rm $name.sam
		#rm $name.bam

		echo
		echo "#######################"
		echo $name DONE!
		echo "#######################"
		echo
		echo
		
	done
	
	cd ..

done

