#!/bin/bash
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N sin113_S1zf_BWA_align
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

## NOTE: changed the ncpus from 2-64 to 1-32 

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

##References:
##Corvus -- Vireo bellii
##Parus -- Auriparus flaviceps
##Sturnus -- Toxostoma curvirostre, Toxostoma crissale, Campylorhynchus brunneicapillus, Polioptila bilineata, Phainopepla nitens
##Zonotrichia -- Amphispiza bilineata, Pipilo fuscus
##Geospiza -- Cardinalis cardinalis, Cardinalis sinuatus

## /home/kprovost/nas3/genomeresequencingFromLucas
## Corv_chrom/  Corv_chrom_parus/  Geos_chrom/  Geos_chrom_parus/  Paru_chrom/  Paru_chrom_parus/  Stur_chrom/  Stur_chrom_parus/  Zono_chrom/  Zono_chrom_parus/
# pseudochromosomes.fasta 

#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Corv_chrom/pseudochromosomes.fasta
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Geos_chrom/pseudochromosomes.fasta
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Paru_chrom/pseudochromosomes.fasta
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Stur_chrom/pseudochromosomes.fasta
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zono_chrom/pseudochromosomes.fasta
 
cd /vz-nas1-active/RawGenomicReads/AMN_245113/sinuatus


date
time

module load bwa-0.7.15
module load fastqc-0.11.5
module load R-3.4.1
#source activate stampy ## NEWLY ADDED from lucas


#for i in */; do  
#	namei="${i///}" ## not there for lucas
#	cd $i; ## not there for lucas
	for read1 in RAPiD-Genomics_*_R1_*; do 
		name2=${read1%_R1_*} ## edited from lucas's
		name=${name2#"RAPiD-Genomics_"}.zf  ## edited from lucas's
		read2=${read1%_R1_*}_R2_*  ## edited from lucas's		
		header=`zcat $read1 | head -1`
		IFS=':' read -a header <<< "$header"
		INSTRUMENT=${header[0]}
		RUN_ID=${header[1]}
		FLOWCELL_BARCODE=${header[2]}
		LANE=${header[3]}
		ID=$FLOWCELL_BARCODE.$LANE
		PU=$FLOWCELL_BARCODE.$LANE.$name
		SM=$name
		PL=ILLUMINA
		LB=TrueSeq
		echo $name $read1 $read2 $ID $PU $SM $PL $LB
	
		echo
		echo "#######################"
		echo $name
		echo "#######################"

		echo
		echo
		echo Trimming adapters
		echo
		echo

		## edited from lucas's, his includes the raw_reads folder 
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/Trimmomatic-0.36/trimmomatic-0.36.jar \
		PE $read1 $read2 \
		$name.forward_paired.fq.gz \
		$name.forward_unpaired.fq.gz \
		$name.reverse_paired.fq.gz \
		$name.reverse_unpaired.fq.gz \
		ILLUMINACLIP:/home/kprovost/nas3/genomeresequencingFromLucas/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa:2:30:10:8:true

		echo
		echo	
		echo Quality assessment
		echo
		echo

		## edited from lucas's, his includes the raw_reads folder 
		time fastqc $name.forward_paired.fq.gz
		time fastqc $name.reverse_paired.fq.gz

		echo
		echo	
		echo Running BWA alignment
		echo
		echo
	
 		if [ ! -d "BAM_files/" ]; then mkdir BAM_files; fi ## added from lucas's 
		time bwa mem \
		-M \
		-t 28 \
		$ref \
		$name.forward_paired.fq.gz \
		$name.reverse_paired.fq.gz \
		> BAM_files/$name.sam ## added from lucas's 

		echo	
		echo
		echo Converting SAM to sorted BAM
		echo
		echo	
	
		## added the BAM_files folders 
		mkdir tmp
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar SortSam \
		INPUT=BAM_files/$name.sam \
		OUTPUT=BAM_files/$name.bam \
		SORT_ORDER=coordinate \
		TMP_DIR=`pwd`/tmp
		rm -r tmp/
		#rm BAM_files/$name.sam ## added from lucas's 

		# this whole section added from lucas in case need to use STAMPY to do anything, but is commented out on his
#       echo
#       echo
#       echo Running Stampy
#       echo
#       echo
# 
#       time stampy -g Picoides_pubescens -h Picoides_pubscens \
#       --bamkeepgoodreads \
#       -M BAM_files/$name.bwa.bam \
#       -t64 \
#       --substitutionrate=0.025 \
#       -o BAM_files/$name.sam
# 	rm BAM_files/$name.bwa.bam
# 
	mkdir tmp
      time java -jar ~/programs/picard/picard.jar SortSam \
      INPUT=BAM_files/$name.sam \
      OUTPUT=BAM_files/$name.bwa.bam \
      SORT_ORDER=coordinate \
      TMP_DIR=`pwd`/tmp
      rm -r tmp/
      rm BAM_files/$name.sam


		## LUCAS'S PIPELINE HAS ADDING READ GROUP AND DEDUPLICATION BEFORE THIS POINT 

		echo
		echo
		echo Adding Read Group
		echo
		echo

 		if [ ! -d "BAM_groupsAdded/" ]; then mkdir BAM_groupsAdded; fi ## added from lucas's 
	
		## added folders from Lucas
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar AddOrReplaceReadGroups \
		I=BAM_files/$name.bam \
		O=BAM_groupsAdded/$name.groups_added.bam \
		RGID=$ID \
		RGLB=$LB \
		RGPL=$PL \
		RGPU=$PU \
		RGSM=$SM
		#rm BAM_files/$name.bam

		echo
		echo Deduplication
		echo
		echo
	
		if [ ! -d "Stats/" ]; then mkdir Stats; fi
 		if [ ! -d "BAM_dedup/" ]; then mkdir BAM_dedup; fi ## added from lucas's 

		## added folders from lucas
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar MarkDuplicates \
		TMP_DIR=tmp \
		I=BAM_groupsAdded/$name.groups_added.bam \
		O=BAM_dedup/$name.dedup.bam \
		METRICS_FILE=Stats/$name.dedup.metrics.txt \
		REMOVE_DUPLICATES=false \
		MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1024 \
		TAGGING_POLICY=All
		#rm -r tmp/
		#rm BAM_groupsAdded/$name.groups_added.bam

		echo	
		echo
		echo Collecting alignment metrics
		echo
		echo
	
		## add this from lucas's 
		if [ ! -d "Stats/" ]; then mkdir Stats; fi
	
		## add folders to this 
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar CollectAlignmentSummaryMetrics \
		INPUT=BAM_files/$name.bam \
		OUTPUT=Stats/$name.alignment_metrics.txt \
		R=$ref \
		METRIC_ACCUMULATION_LEVEL=SAMPLE \
		METRIC_ACCUMULATION_LEVEL=READ_GROUP \

		echo
		echo
		echo Collect Insert Size Metrics
		echo
		echo
		## add folders to this
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar CollectInsertSizeMetrics \
		INPUT=BAM_files/$name.bam \
		OUTPUT=Stats/$name.insert_metrics.txt \
		HISTOGRAM_FILE=Stats/$name.insert_size_histogram.pdf

		echo
		echo
		echo Collect Coverage Metrics
		echo
		echo
		## add folders to this
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar CollectRawWgsMetrics \
		I=BAM_files/$name.bam \
		O=Stats/$name.raw_wgs_metrics.txt \
		R=$ref \
		INCLUDE_BQ_HISTOGRAM=true
	
		#rm $name.sam
		#rm $name.bam

		## AFTER THIS STEP LUCAS RUNS INDEXING AND QUALIMAP 
		
		echo
		echo
		echo Indexing BAM
		echo
		echo
	
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar BuildBamIndex \
		I=BAM_dedup/$name.dedup.bam ## folder added from lucas
		
		echo
		echo
        echo Running QUALIMAP
        echo
        echo

		## copied from lucas 
		time qualimap bamqc -nt 8 -bam BAM_dedup/$name.dedup.bam -outdir Stats/$name.QUALIMAP --java-mem-size=8G 

		echo
		echo "#######################"
		echo $name DONE!
		echo "#######################"
		echo
		echo
		
	done
	
	cd ..

done


