#!/bin/bash
#PBS -l select=1:ncpus=2
#PBS -l walltime=5000:00:00
#PBS -N cur_ANGSD_GL
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## bam_list = list of BAM files

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

date
time

time /home/kprovost/nas3/angsd/angsd -GL 2 \
-doMajorMinor 1 \
-doMaf 1 \
-doGlf 2 \
-minMaf 0.05 \
-SNP_pval 0.01 \
-minInd 4 \
-minMapQ 20 \
-minQ 20 \
-nThreads 16 \
-bam /home/kprovost/nas3/ANGSD_pipeline/Toxostoma-curvirostre.bamlist \
-out Toxostoma-curvirostre
