#!/bin/bash
#PBS -l select=1:ncpus=2
#PBS -l walltime=5000:00:00
#PBS -N nitCHI_ANGSD_GL
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## bam_list = list of BAM files
## the indlists for CHI and chi work for this
bamlist=/home/kprovost/nas3/ANGSD_pipeline/CHI_Phainopepla_nitens.indlist

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

## https://github.com/mfumagalli/ngsPopGen/blob/master/snitpts/calcDxy.R

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Stur_chrom/pseudochromosomesSHORT.fasta

##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo

date
time

echo "index file"

# for i in Phainopepla-nitens.*; do
# echo $i
# sitesfile=$i
# time /home/kprovost/nas3/angsd/angsd sites index $sitesfile
# echo "" 

echo "run for CHI"

time /home/kprovost/nas3/angsd/angsd -GL 2 \
-doMajorMinor 1 \
-doMaf 1 \
-doGlf 2 \
-minMaf 0.05 \
-skipTriallelic \
-ref $ref \
-minMapQ 20 \
-minQ 20 \
-nThreads 16 \
-bam $bamlist \
-out Phainopepla-nitens-CHIDXY

## took out: #-sites /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/Phainopepla-nitens-DXY.beagle \
## took out: #-minInd 4 \

