#!/bin/bash
#PBS -l select=1:ncpus=64
#PBS -l walltime=5000:00:00
#PBS -N GATKsnpGVCFsinuatus
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Geospiza_fortis_GCF_000277835.1_GeoFor_1.0_genomic.fna 

cd /home/kprovost/nas3/AMN_245107/sequences/sinuatus/


echo
echo
echo Combine GVCFs
echo
echo

time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar \
-T GenotypeGVCFs \
-R $ref \
--variant AMN_245107_P01_WA03_sinuatus.recal.raw.g.vcf \
--variant AMN_245107_P01_WB03_sinuatus.recal.raw.g.vcf \
--variant AMN_245107_P01_WC03_sinuatus.recal.raw.g.vcf \
--variant AMN_245107_P01_WH02_sinuatus.recal.raw.g.vcf \
--variant GW180220900_AMN_245107_P01_WD03_sinuatus.recal.raw.g.vcf \
--variant GW180323979_AMN_245107_P01_WD03_sinuatus.recal.raw.g.vcf \
-o sinuatus.allsamples.recal.raw.vcf \
-nt 64
##### nt not there originally, didn't have slash before