#!/bin/bash
#PBS -l select=1:ncpus=32
#PBS -l walltime=5000:00:00
#PBS -N fus_50SONtaj
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zono_chrom/pseudochromosomesSHORT.fasta

bamlist=/home/kprovost/nas3/ANGSD_pipeline/SON_Melozone_fusca_50.indlist

for i in /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/MISSINGBAMS/fusca/*gz; do
echo $i; gunzip $i; done

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

date
time

if [ ! -f "Melozone_fusca-50-SON-taj1.saf.gz" ]; then
time /home/kprovost/nas3/angsd/angsd -bam $bamlist -doSaf 1 -anc $ref -GL 1 -P 24 -out Melozone_fusca-50-SON-taj1
fi

if [ ! -f "Melozone_fusca-50-SON-taj1.saf.idx" ]; then
gunzip -vf Melozone_fusca-50-SON-taj1.saf.gz
/home/kprovost/nas3/htslib/bgzip -c Melozone_fusca-50-SON-taj1.saf > Melozone_fusca-50-SON-taj1.saf.gz
/home/kprovost/nas3/htslib/tabix -p vcf Melozone_fusca-50-SON-taj1.saf.gz
fi

if [ ! -f "Melozone_fusca-50-SON-taj.sfs" ]; then
time /home/kprovost/nas3/angsd/misc/realSFS \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/Melozone_fusca-50-SON-taj1.saf.idx \
> Melozone_fusca-50-SON-taj.sfs
fi

time /home/kprovost/nas3/angsd/angsd -GL 2 -bam $bamlist -doThetas 1 -doSaf 1 -pest Melozone_fusca-50-SON-taj.sfs -anc $ref -out Melozone_fusca-50-SON-taj2 

#Estimate for every Chromosome/scaffold
time /home/kprovost/nas3/angsd/misc/thetaStat do_stat \
Melozone_fusca-50-SON-taj2.thetas.idx

#Do a sliding window analysis based on the output from the make_bed command.
time /home/kprovost/nas3/angsd/misc/thetaStat do_stat \
Melozone_fusca-50-SON-taj2.thetas.idx \
-win 100000 \
-step 10000  \
-outnames Melozone_fusca-50-SON-taj2.thetasWindow.gz