#!/bin/bash
#PBS -l select=1:ncpus=16
#PBS -l walltime=5000:00:00
#PBS -N bruCHI_S6_GATKSNPBQSR
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Corvus_brachyrhynchus_GCF_000691975.1_ASM69197v1_genomic.fna
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Geospiza_fortis_GCF_000277835.1_GeoFor_1.0_genomic.fna
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Parus_major_GCF_001522545.2_Parus_major1.1_genomic.fna
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Strunus_vulgaris_GCF_001447265.1_Sturnus_vulgaris-1.0_genomic.fna
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zonotrichia_albicollis_GCF_000385455.1_Zonotrichia_albicollis-1.0.1_genomic.fna

##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, bruozone

## bam=bam file
## NOTE: this runs on a job by job basis 

## /vz-nas1-active/ProcessedGenomicReads/AMN_245107/brunneicapillus/December_Rerun/BAM_files
## /vz-nas1-active/ProcessedGenomicReads/AMN_245109/Plate2/brunneicapillus/December_Rerun/BAM_files
## /vz-nas1-active/ProcessedGenomicReads/AMN_245111/Plate2/brunneicapillus/December_Rerun/BAM_files

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/
vcf=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/brunneicapillus107-109-111_CHI.combined.db.vcf

#name=`echo $bam | cut -d '/' -f2 | cut -d '.' -f1` ## lucas's version 
#name=$(echo $bam | cut -f 1 -d '.')

echo
echo "#######################"
echo $bam
echo $name
echo "#######################"

echo
echo
echo BQSR
echo
echo

## NOTE: this step is very different. old version bruow new. 
## note folder names added 
time java -Djava.io.tmpdir=/home/kprovost/nas3/tmp/ -jar /home/kprovost/nas3/genomeresequencingFromLucas/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar -T BaseRecalibrator \
-R $ref \
-I $bam \
-knownSites $vcf \
-o BAM_files/$name.recal_data.grp \
-nct 32

time java -Djava.io.tmpdir=/home/kprovost/nas3/tmp/ -jar /home/kprovost/nas3/genomeresequencingFromLucas/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar -T BaseRecalibrator \
-R $ref \
-I $bam \
-knownSites $vcf \
-BQSR BAM_files/$name.recal_data.grp \
-o BAM_files$name.post_recal_data.grp \
-nct 32

time java -Djava.io.tmpdir=/home/kprovost/nas3/tmp/ -jar /home/kprovost/nas3/genomeresequencingFromLucas/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar -T AnalyzeCovariates \
-R $ref \
-before BAM_files/$name.recal_data.grp \
-after BAM_files/$name.post_recal_data.grp \
-plots BAM_files/$name.recalibration_plots.pdf

## old version
# time java -Djava.io.tmpdir=/home/kprovost/nas3/tmp/ -jar /home/kprovost/nas3/genomeresequencingFromLucas/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar -T BaseRecalibrator \
# -R $ref \
# -I $bam \
# -knownSites /home/kprovost/nas3/EVERY_PLATE/brunneicapillus/brunneicapillus_batch2.combined.db.vcf \
# -o $name.recal_data.grp \
# -nct 32

echo
echo
echo Producing recalibrated VCF file
echo
echo

## added folders 
time java -Djava.io.tmpdir=/home/kprovost/nas3/tmp/ -jar /home/kprovost/nas3/genomeresequencingFromLucas/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar -T HaplotypeCaller \
-R $ref \
-I $bam \
-o vcf_files/$name.recal.raw.g.vcf \
--emitRefConfidence GVCF \
-minPruning 1 \
-minDanglingBranchLength 1 \
-BQSR BAM_files/$name.recal_data.grp \
-nct 32
