#!/bin/bash
#PBS -l select=1:ncpus=1:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N fla0_beagle_windows
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

spp="Auriparus-flaviceps"

window=0 ## alt = 0

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/

mkdir $spp/
cd $spp/

for i in ${spp}.beagle.gz; do 
echo $i

#gzip $spp.beagle


if [ "$window" -eq "0" ]; then
echo "ZERO"
zcat /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/$spp.beagle.gz | awk 'FNR==1{header=$0; next} {match($1,".*_",tmp); chr=substr(tmp[0],1,length(tmp[0])-1); split($1,tmp,"_"); pos=tmp[length(tmp)]; file = chr"."int(pos/1000000000)".F.beagle"} outfile != file{outfile = file; print header > outfile} {print $0 > outfile}'
else
echo "ONE"
zcat /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/$spp.beagle.gz | awk 'FNR==1{header=$0; next} {match($1,".*_",tmp); chr=substr(tmp[0],1,length(tmp[0])-1); split($1,tmp,"_"); pos=tmp[length(tmp)]; file = chr"."int(pos/100000)".beagle"} outfile != file{outfile = file; print header > outfile} {print $0 > outfile}'
fi


done

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/

mv ${spp}*beagle $spp/