#!/bin/bash
#PBS -l select=1:ncpus=1:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N Par_beagle_windows
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

spp="Parrots"

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/

gzip $spp.beagle

mkdir $spp/
cd $spp/

zcat /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/$spp.beagle.gz | awk 'FNR==1{header=$0; next} {match($1,".*_",tmp); chr=substr(tmp[0],1,length(tmp[0])-1); split($1,tmp,"_"); pos=tmp[length(tmp)]; file = chr"."int(pos/50000)".beagle"} outfile != file{outfile = file; print header > outfile} {print $0 > outfile}'

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/

mv *beagle $spp/