#!/bin/bash
#PBS -l select=1:ncpus=32:mem=128gb
#PBS -l walltime=5000:00:00
#PBS -N fus75-NW_sfsA
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zono_chrom/pseudochromosomesSHORT.fasta

## bam_list = list of BAM files
bamlist=/home/kprovost/nas3/ANGSD_pipeline/Melozone_fusca_NOWEIRD_75.bamlist

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

date
time

time /home/kprovost/nas3/angsd/angsd -GL 2 \
-dosaf 1 \
-fold 1 \
-minInd 4 \
-minMapQ 20 \
-minQ 20 \
-nThreads 16 \
-ref $ref \
-anc $ref \
-bam $bamlist \
-out Melozone-fusca-NOWEIRD-75-sfs1