#!/bin/bash
#PBS -l select=1:ncpus=32
#PBS -l walltime=5000:00:00
#PBS -N cri_75taj
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

ref=/home/kprovost/nas3/genomeresequencingFromLucas/Stur_chrom/pseudochromosomesSHORT.fasta

bamlist=/home/kprovost/nas3/ANGSD_pipeline/Toxostoma_crissale_75.bamlist

for i in /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/MISSINGBAMS/crissale/*gz; do
echo $i; gunzip $i; done

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

date
time

if [ ! -f "Toxostoma_crissale-75-taj1.saf.gz" ]; then
time /home/kprovost/nas3/angsd/angsd -bam $bamlist -doSaf 1 -anc $ref -GL 1 -P 24 -out Toxostoma_crissale-75-taj1
fi

if [ ! -f "Toxostoma_crissale-75-taj1.saf.idx" ]; then
gunzip -vf Toxostoma_crissale-75-taj1.saf.gz
/home/kprovost/nas3/htslib/bgzip -c Toxostoma_crissale-75-taj1.saf > Toxostoma_crissale-75-taj1.saf.gz
/home/kprovost/nas3/htslib/tabix -p vcf Toxostoma_crissale-75-taj1.saf.gz
fi

if [ ! -f "Toxostoma_crissale-75-taj.sfs" ]; then
time /home/kprovost/nas3/angsd/misc/realSFS \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/Toxostoma_crissale-75-taj1.saf.idx \
> Toxostoma_crissale-75-taj.sfs
fi

time /home/kprovost/nas3/angsd/angsd -GL 2 -bam $bamlist -doThetas 1 -doSaf 1 -pest Toxostoma_crissale-75-taj.sfs -anc $ref -out Toxostoma_crissale-75-taj2 

#Estimate for every Chromosome/scaffold
time /home/kprovost/nas3/angsd/misc/thetaStat do_stat \
Toxostoma_crissale-75-taj2.thetas.idx

#Do a sliding window analysis based on the output from the make_bed command.
time /home/kprovost/nas3/angsd/misc/thetaStat do_stat \
Toxostoma_crissale-75-taj2.thetas.idx \
-win 100000 \
-step 10000  \
-outnames Toxostoma_crissale-75-taj2.thetasWindow.gz