#!/bin/bash
#PBS -l select=1:ncpus=2
#PBS -l walltime=5000:00:00
#PBS -N bil_callsnp_angsd
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## bam_list = list of BAM files
## the indlists for son and chi work for this
bamlist=/home/kprovost/nas3/ANGSD_pipeline/Amphispiza-bilineata.bamlist

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

date
time

time /home/kprovost/nas3/angsd/angsd -GL 2 \
-bam $bamlist \
-doGeno 5 \
-doGlf 2 \
-doMaf 1 \
-doMajorMinor 1 \
-doPost 1 \
-doVcf \
-minInd 4 \
-minMaf 0.05 \
-minMapQ 20 \
-minQ 20 \
-nThreads 16 \
-postCutoff 0.95 \
-SNP_pval 0.01 \
-out Amphispiza-bilineata-called 