#!/bin/bash
#PBS -l select=1:ncpus=16
#PBS -l walltime=5000:00:00
#PBS -N bel_son_rscript
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

sonmaf=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/MAFS/Vireo-bellii-SONDXY.mafs
chimaf=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/MAFS/Vireo-bellii-CHIDXY.mafs

## don't think you need totLen to generate the Dxy thing 

echo "son maf file is: ${sonmaf}"
echo "chi maf file is: ${chimaf}"

perl /home/kprovost/nas3/ANGSD_pipeline/ngsTools/ngsPopGen/scripts/getDxy.pl \
--pop1maf $sonmaf \
--pop2maf $chimaf \
--minInd 2

mv Dxy_persite.txt bel_SON_Dxy_persite.txt

perl /home/kprovost/nas3/ANGSD_pipeline/ngsTools/ngsPopGen/scripts/getDxy.pl \
--pop1maf $chimaf \
--pop2maf $sonmaf \
--minInd 2

mv Dxy_persite.txt bel_CHI_Dxy_persite.txt
