#!/bin/bash
#PBS -l select=1:ncpus=16
#PBS -l walltime=5000:00:00
#PBS -N ngsdist_2022
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## GL = genotype likehood file (Beagle format)

for GL in /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/*_1.0.F*beagle.gz; do
echo $GL

if [ ! -f ${GL}_ngsdist_2022.txt ]
then
    echo "RUN"

#GL="/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/Vireo_bellii/Vireo_bellii_75.bamlist.beagle.gz.PseudoNC_011495.1_Tgut_LG5.0.F.beagle.gz"
lines=`zcat $GL | wc -l`
sites="$(($lines-1))"
## individuals = the number of things in the header minus 3 divided by 3
header=`zcat $GL | head -n 1`
headerN=`echo -n "${header}" | wc -w`
indsN3="$(($headerN/3))"
indsN="$(($indsN3-1))"

cd "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/"

echo date
echo time

/home/lmoreira/programs/ngsTools/ngsDist/ngsDist \
--n_threads 16 \
--geno $GL \
--n_ind $indsN \
--n_sites $sites \
--out "${GL}_ngsdist_2022.txt"
fi
done

## REMOVED:
# --n_boot_rep 300 \
# --boot_block_size 500 \


## sites is how many sites in GL file zcat <file> | wc -l (-1 because of header)
## 27194088

## changed to $GL from the raw format itself

# =====
# ERROR: [read_geno] wrong GENO file format. Less fields than expected!
# =====
