#!/bin/bash
#PBS -l select=1:ncpus=1:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N Par_geno2vcf
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/GENO/

source activate py36

#gunzip Auriparus-flaviceps-called.geno.gz 

geno=Auriparus-flaviceps-called.geno

python3 /home/kprovost/nas3/ANGSD_pipeline/angsdgeno2vcf.py $geno

python3 /home/kprovost/nas3/ANGSD_pipeline/vcf_remove_2tabs.py $geno.vcf

mv $geno.vcf /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/ 