#!/bin/bash
#PBS -l select=1:ncpus=1:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N Par_vcf2chrom
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

spp="Parrots"

#cd "/Users/kprovost/Documents/folder_for_popgenome/"
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/

for i in ${spp}*vcf; do
echo $i 
j=${i%.vcf}
mkdir ./${j}

#/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java \
#-jar /Users/kprovost/Documents/folder_for_popgenome/snpEff_latest_core/snpEff/SnpSift.jar split $i

java -Djava.io.tmpdir=/home/kprovost/nas3/tmp/ -jar /home/kprovost/nas3/ANGSD_pipeline/SnpSift.jar split $i

gzip $i

mv ./${j}*.vcf ./${j}

done; 