#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=99999:00:00
#PBS -N vcf2ldhat
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
#cd $PBS_O_WORKDIR
#echo "pbsworkdir"
#echo $PBS_O_WORKDIR
#EXECDIR=`pwd`
#export PATH=./:$PATH
#echo $PATH

##/home/kprovost/nas3/plink-1.07-x86_64/plink/ 
## --recode-structure 

## arguments
## vcf

## you have to do this one chromosome at a time unfortunately -- wait until you have chrom level bams 

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/
for folder in V*/; do 
folder=${folder%/}
echo "folder: $folder"
#folder=Vireo-bellii-called.geno
cd $folder
for vcf in *16.vcf; do
#vcf=$folder/$folder.PseudoNC_011480.1_Tgut_16.vcf
echo "vcf: $vcf"
## check if file  exists 
#if [ ! -f $vcf.ldhat.ldhat.sites ]
#then 
chrom=${vcf%.vcf}
chrom=${chrom#$folder.}
echo "chrom: $chrom"
/home/kprovost/opt/bin/vcftools --vcf $vcf --chr $chrom --ldhat-geno --out $vcf.ldhat
#fi
done
mv *ldhat* /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/LDHAT/
cd ..
done

#vcftools --vcf "$vcf" --chr "NW_014650461.1" --ldhat-geno --out testing
## add the ldhat commands
#pairqise -seq <file_name> -loc <file_name> -l <file_name>
