#!/bin/bash
#PBS -l select=1:ncpus=8:mem=64gb
#PBS -l walltime=5000:00:00
#PBS -N fstout_vcf_subset
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe


#rclone copy -v remote:/Huxley_Backup_20August2020/VCFS/FUSCA/GENOME/Melozone-fusca_fixed.sorted.nospace.sorted.nospace.vcf.gz /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/

# vcffile=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/Amphispiza-bilineata-called.geno_COMBINED.fixedchroms.sorted.nospace.vcf.gz
# smallfile=/home/kprovost/nas3/LOSTRUCT/bil.fstoutlier.small.csv
# python3 /home/kprovost/nas3/LOSTRUCT/vcf_extract_fstoutlier_windows.py $vcffile $smallfile

# vcffile=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/Auriparus-flaviceps-called.geno.PseudoNC.all.sorted.sorted.sorted.nospace.vcf.gz
# smallfile=/home/kprovost/nas3/LOSTRUCT/fla.fstoutlier.small.csv
# python3 /home/kprovost/nas3/LOSTRUCT/vcf_extract_fstoutlier_windows.py $vcffile $smallfile

# vcffile=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/Campylorhynchus-brunneicapillus-called.geno.PseudoNC.all.fixedchroms.converted.sorted.sorted.sorted.nospace.vcf.gz
# smallfile=/home/kprovost/nas3/LOSTRUCT/bru.fstoutlier.small.csv
# python3 /home/kprovost/nas3/LOSTRUCT/vcf_extract_fstoutlier_windows.py $vcffile $smallfile

# vcffile=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/Cardinalis-sinuatus-called.geno.PseudoNC.all.fixedchroms.converted.sorted.sorted.sorted.copy.nospace.vcf.gz
# smallfile=/home/kprovost/nas3/LOSTRUCT/sin.fstoutlier.small.csv
# python3 /home/kprovost/nas3/LOSTRUCT/vcf_extract_fstoutlier_windows.py $vcffile $smallfile

# vcffile=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/Melozone-fusca_fixed.sorted.nospace.sorted.nospace.vcf.gz
# smallfile=/home/kprovost/nas3/LOSTRUCT/fus.fstoutlier.small.csv
# python3 /home/kprovost/nas3/LOSTRUCT/vcf_extract_fstoutlier_windows.py $vcffile $smallfile

# vcffile=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/Phainopepla-nitens-called.geno.PseudoNC.all.fixedchroms.converted.sorted.sorted.sorted.nospace.vcf.gz
# smallfile=/home/kprovost/nas3/LOSTRUCT/nit.fstoutlier.small.csv
# python3 /home/kprovost/nas3/LOSTRUCT/vcf_extract_fstoutlier_windows.py $vcffile $smallfile

# vcffile=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/Polioptila-melanura-called.geno.PseudoNC.all.fixedchroms.converted.sorted.sorted.sorted.nospace.vcf.gz
# smallfile=/home/kprovost/nas3/LOSTRUCT/mel.fstoutlier.small.csv
# python3 /home/kprovost/nas3/LOSTRUCT/vcf_extract_fstoutlier_windows.py $vcffile $smallfile

# vcffile=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/Toxostoma-crissale-called.geno.PseudoNC.all.fixedchroms.converted.sorted.sorted.sorted.nospace.vcf.gz
# smallfile=/home/kprovost/nas3/LOSTRUCT/cri.fstoutlier.small.csv
# python3 /home/kprovost/nas3/LOSTRUCT/vcf_extract_fstoutlier_windows.py $vcffile $smallfile

# vcffile=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/Toxostoma-curvirostre-called.geno.PseudoNC.all.fixedchroms.converted.sorted.sorted.sorted.nospace.vcf.gz
# smallfile=/home/kprovost/nas3/LOSTRUCT/cur.fstoutlier.small.csv
# python3 /home/kprovost/nas3/LOSTRUCT/vcf_extract_fstoutlier_windows.py $vcffile $smallfile

vcffile=/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/Vireo-bellii-called.geno.PseudoNC.all.sorted.sorted.vcf.gz
smallfile=/home/kprovost/nas3/LOSTRUCT/bel.fstoutlier.small.csv
python3 /home/kprovost/nas3/LOSTRUCT/vcf_extract_fstoutlier_windows.py $vcffile $smallfile