#!/bin/bash
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N bel_sfs3
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Corv_chrom/pseudochromosomesSHORT.fasta

##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo

## bam_list = list of BAM files
# sonlist=/home/kprovost/nas3/ANGSD_pipeline/SON_Vireo_bellii.indlist
# chilist=/home/kprovost/nas3/ANGSD_pipeline/CHI_Vireo_bellii.indlist

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

date
time


## now get the 2d sfs for each 
# time /home/kprovost/nas3/angsd/misc/realSFS \
# SON_CHI_Vireobellii.ml.1D.txt

## convert ml files to single lines or first lines or something
## need mean values 




## may need to do the ml files with means? 

echo "Prep for window analysis"

#/home/kprovost/nas3/angsd/angsd sites index /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Vireo_bellii-sfs1.saf.pos.gz

## failing to open idx 

# prepare the fst for easy window analysis etc
# ../misc/realSFS fst index pop1.saf.idx pop2.saf.idx -sfs pop1.pop2.ml.1D.txt -fstout here
time /home/kprovost/nas3/angsd/misc/realSFS fst index \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Vireo_bellii-sfs1.saf.idx \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Vireo_bellii-sfs1.saf.idx \
-sfs /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/MLFILES/SON_CHI_Vireo_bellii.ml.1D.txt.1D \
-fstout /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SON_CHI_Vireo_bellii_FST 

echo "Get global estimate"

# get the global estimate
# ../misc/realSFS fst stats here.fst.idx 
# -> FST.Unweight:0.069395 Fst.Weight:0.042349
time /home/kprovost/nas3/angsd/misc/realSFS fst stats \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/FSTFILES/SON_CHI_Vireo_bellii_FST.fst.idx 

echo "Sliding Windows" 

# below is not tested that much, but seems to work
## this window seems too large
# ../misc/realSFS fst stats2 here.fst.idx -win 100000 -step 10000 >slidingwindow
time /home/kprovost/nas3/angsd/misc/realSFS  fst stats2 \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SON_CHI_Vireo_bellii_FST.fst.idx \
-win 100000 -step 10000 > /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SON_CHI_Vireo_bellii_FST_slidingwindow.fst