#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=99999:00:00
#PBS -N ldhat_pairwise
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
#cd $PBS_O_WORKDIR
#echo "pbsworkdir"
#echo $PBS_O_WORKDIR
#EXECDIR=`pwd`
#export PATH=./:$PATH
#echo $PATH

##/home/kprovost/nas3/plink-1.07-x86_64/plink/ 
## --recode-structure 

## arguments
## vcf

## For diploid data need complete lookup table for sequences
## need to change this to do 1 file at a time, clip overlap style? 


cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/LDHAT/

for sites in *PseudoNC*.vcf.ldhat.ldhat.sites
do
echo "Sites: $sites"  > $sites.log 2>&1

locs=${sites%.sites}.locs
echo "Locs: $locs"  > $sites.log 2>&1

numinds=$((2*`grep -o '>' $sites | wc -l`))
echo "Num inds: $numinds"  > $sites.log 2>&1

if [ ! "$numinds" -eq "0" ]; then

lkname1=/home/kprovost/nas3/LDHAT/lk_n${numinds}_t0.001
lkname2=/home/kprovost/nas3/LDHAT/lk_n${numinds}_t0.1
lkname3=/home/kprovost/nas3/LDHAT/lk_n${numinds}_t0.5
lkname4=/home/kprovost/nas3/LDHAT/lk_n${numinds}_t0.01

echo "checking lknames"  > $sites.log 2>&1
if [ ! -f $lkname1 ]
then
/home/kprovost/nas3/LDHAT/LDhat/lkgen -lk /home/kprovost/nas3/LDHAT/lk_n50_t0.001 -nseq $numinds > $sites.log 2>&1
mv new_lk.txt $lkname1
fi

if [ ! -f $lkname2 ]
then
/home/kprovost/nas3/LDHAT/LDhat/lkgen -lk /home/kprovost/nas3/LDHAT/lk_n50_t0.1 -nseq $numinds > $sites.log 2>&1
mv new_lk.txt $lkname2
fi

if [ ! -f $lkname3 ]
then
/home/kprovost/nas3/LDHAT/LDhat/lkgen -lk /home/kprovost/nas3/LDHAT/lk_n50_t0.5 -nseq $numinds > $sites.log 2>&1
mv new_lk.txt $lkname3
fi

if [ ! -f $lkname4 ]
then
/home/kprovost/nas3/LDHAT/LDhat/lkgen -lk /home/kprovost/nas3/LDHAT/lk_n100_t0.01 -nseq $numinds > $sites.log 2>&1
mv new_lk.txt $lkname4
fi

time /home/kprovost/nas3/LDHAT/LDhat/pairwise -concise -seq $sites -loc $locs -lk $lkname2 > $sites.log 2>&1

mv outfile.txt $sites.outfile.txt
mv new_lk.txt $sites.new_lk.txt
mv fits.txt $sites.fits.txt
mv window_out.txt $sites.window_out.txt
mv rmin.txt $sites.rmin.txt
mv rdist.txt $sites.rdist.txt
mv sim_out.txt $sites.sim_out.txt

fi

done 