#!/bin/bash
#PBS -l select=1:ncpus=32
#PBS -l walltime=5000:00:00
#PBS -N QUALIMAP
#PBS -j oe
#PBS -m ae
#PBS -M lmoreira@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

for filename in *.dedup.bam; do
	name=$(echo $filename | cut -f 1 -d '.')
	qualimap bamqc -nt 8 -bam $filename -outdir $name.QUALIMAP
done

