#!/bin/bash
#PBS -l select=1:ncpus=16
#PBS -l walltime=5000:00:00
#PBS -N bru111_S1.2_merge_bam2
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#cd /vz-nas1-active/ProcessedGenomicReads/PARUS_MAJOR/brunneicapillus/
#cd /vz-nas1-active/ProcessedGenomicReads/PARUS_MAJOR/brunneicapillus/
cd /vz-nas1-active/ProcessedGenomicReads/PARUS_MAJOR/brunneicapillus/



if [ ! -d "Stats/" ]; then mkdir Stats; fi

#prefix="GW18" ## 107
#prefix="F067" ## 109
prefix="F073" ## 111
	
suffix=".dedup.bam";
for bam in $prefix*$suffix; do 
name=$(echo $bam | cut -d "_" -f 2-5); 

echo
echo "#######################"
echo $name
echo "#######################"

echo
echo
echo Merging Bam Files
echo
echo



command="time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar MarkDuplicates TMP_DIR=tmp "
#command="time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar MergeSamFiles ";
for i in *$name*$suffix; do command="${command}I=${i} "; 
done; 
merged="${name}_brunneicapillus.merged${suffix}"
command="${command} O=${merged}"
command="${command} METRICS_FILE=Stats/$name.merged.dedup.metrics.txt REMOVE_DUPLICATES=false MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1024 TAGGING_POLICY=All"
echo
echo
echo "COMMAND IS:"
echo $command
echo
echo
eval $command
done;