#!/bin/bash
#PBS -l select=1:ncpus=16
#PBS -l walltime=5000:00:00
#PBS -N parrots_S1.1_merge_bam
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

cd /vz-nas1-active/RawGenomicReads/FASTQ_SCREEN_RESULTS/Parrots/BAM_dedup/

prefix="F119" ##
	
for bam in $prefix*.bam; do 
name=$(echo $bam | cut -d "_" -f 2-5); 

echo
echo "#######################"
echo $name
echo "#######################"

echo
echo
echo Merging Bam Files
echo
echo

## Exception in thread "main" htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequence dictionaries are not the same size (0, 17995) 

command="time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar MergeSamFiles ";
for i in *$name*bam; do 
command="${command}I=${i} "; 
done; 
#echo $command;
merged="${name}_Parrots.bam"
command="${command} O=${merged}"
echo $command
eval $command
done;


