#!/bin/bash
#PBS -l select=1:ncpus=32:mem=128gb
#PBS -l walltime=99999:00:00
#PBS -N fla_sfs2
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Paru_chrom/pseudochromosomesSHORT.fasta

##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo

## bam_list = list of BAM files
sonlist=/home/kprovost/nas3/ANGSD_pipeline/SON_Auriparus_flaviceps.indlist
chilist=/home/kprovost/nas3/ANGSD_pipeline/CHI_Auriparus_flaviceps.indlist

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

rm fla_sfs2.logfile

date >> fla_sfs2.logfile 2>&1
time >> fla_sfs2.logfile 2>&1

## get the global sfs
# echo "GLOBAL SFS" >> fla_sfs2.logfile 2>&1
# time /home/kprovost/nas3/angsd/misc/realSFS -nSites 50000000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/Auriparus_flaviceps-sfs1.saf.idx >> fla_sfs2.logfile 2>&1

## get the by population sfs 
# echo >> fla_sfs2_SON.logfile 2>&1
# echo "SON SFS" >> fla_sfs2_SON.logfile 2>&1
# /home/kprovost/nas3/angsd/angsd -b $sonlist \
# -anc $ref \
# -out SON_Auriparus_flaviceps-sfs1 \
# -dosaf 1 \
# -gl 1 >> fla_sfs2_SON.logfile 2>&1
# 
# mv SON_Auriparus_flaviceps-sfs1* /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/

# echo >> fla_sfs2_CHI.logfile 2>&1
# echo "CHI SFS" >> fla_sfs2_CHI.logfile 2>&1
# /home/kprovost/nas3/angsd/angsd -b $chilist \
# -anc $ref \
# -out CHI_Auriparus_flaviceps-sfs1 \
# -dosaf 1 \
# -gl 1 >> fla_sfs2_CHI.logfile 2>&1
# 
# ## now get the 2d sfs for each 
# 
# mv CHI_Auriparus_flaviceps-sfs1* /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/

#works 1204964 not 1204965
## problem is with site 1204965 in SON file -- redo?
command="time /home/kprovost/nas3/angsd/misc/realSFS \
-nSites 50000000 \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Auriparus_flaviceps-sfs1.saf.idx \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Auriparus_flaviceps-sfs1.saf.idx \
> SON_CHI_Auriparus_flaviceps.ml"
eval $command >> fla_sfs2.logfile 2>&1
