#!/bin/bash
#PBS -l select=1:ncpus=2:mem=128gb
#PBS -l walltime=99999:00:00
#PBS -N bil_sfs2
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zono_chrom/pseudochromosomesSHORT.fasta

## bam_list = list of BAM files
sonlist=/home/kprovost/nas3/ANGSD_pipeline/SON_Amphispiza_bilineata.indlist
chilist=/home/kprovost/nas3/ANGSD_pipeline/CHI_Amphispiza_bilineata.indlist

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

rm bil_sfs2.logfile

date >> bil_sfs2.logfile 2>&1
time >> bil_sfs2.logfile 2>&1

## get the global sfs
# echo "GLOBAL SFS" >> bil_sfs2.logfile 2>&1
# time /home/kprovost/nas3/angsd/misc/realSFS -nSites 50000000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/Amphispiza_bilineata-sfs1.saf.idx >> bil_sfs2.logfile 2>&1

## get the by population sfs 
# echo >> bil_sfs2.logfile 2>&1
# echo "SON SFS" >> bil_sfs2.logfile 2>&1
# /home/kprovost/nas3/angsd/angsd -b $sonlist \
# -anc $ref \
# -out SON_Amphispiza_bilineata-sfs1 \
# -dosaf 1 \
# -gl 1 >> bil_sfs2.logfile 2>&1

# echo >> bil_sfs2.logfile 2>&1
# echo "CHI SFS" >> bil_sfs2.logfile 2>&1
# /home/kprovost/nas3/angsd/angsd -b $chilist \
# -anc $ref \
# -out CHI_Amphispiza_bilineata-sfs1 \
# -dosaf 1 \
# -gl 1 >> bil_sfs2.logfile 2>&1

## now get the 2d sfs for each 

command="time /home/kprovost/nas3/angsd/misc/realSFS -nSites 50000000 \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Amphispiza_bilineata-sfs1.saf.idx \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Amphispiza_bilineata-sfs1.saf.idx \
> SON_CHI_Amphispiza_bilineata.ml"
eval $command >> bil_sfs2.logfile 2>&1