#!/bin/bash
#PBS -l select=1:ncpus=2:mem=64gb
#PBS -l walltime=99999:00:00
#PBS -N nit_sfs2
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Stur_chrom/pseudochromosomesSHORT.fasta

##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo

## bam_list = list of BAM files
sonlist=/home/kprovost/nas3/ANGSD_pipeline/SON_Phainopepla_nitens.indlist
chilist=/home/kprovost/nas3/ANGSD_pipeline/CHI_Phainopepla_nitens.indlist

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

date
time

# time /home/kprovost/nas3/angsd/angsd -GL 2 \
# -dosaf 1 \
# -fold 1 \
# -minInd 4 \
# -minMapQ 20 \
# -minQ 20 \
# -nThreads 16 \
# -ref $ref \
# -anc $ref \
# -bam $indlist \
# -out Phainopepla_nitens

## get the global sfs
echo "GLOBAL SFS"
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 50000000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/Phainopepla_nitens-sfs1.saf.idx

## get the by population sfs 
echo 
echo "SON SFS"
/home/kprovost/nas3/angsd/angsd -b $sonlist \
-anc $ref \
-out SON_Phainopepla_nitens-sfs1 \
-dosaf 1 \
-gl 1

# echo 
# echo "SKIPPING CHI BECAUSE NO SAMPLES"

echo 
echo "CHI SFS"
/home/kprovost/nas3/angsd/angsd -b $chilist \
-anc $ref \
-out CHI_Phainopepla_nitens-sfs1 \
-dosaf 1 \
-gl 1

## now get the 2d sfs for each 
time /home/kprovost/nas3/angsd/misc/realSFS \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SON_Phainopepla_nitens-sfs1.saf.idx \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/CHI_Phainopepla_nitens-sfs1.saf.idx \
> SON_CHI_Phainopepla_nitens.ml

# first calculate per pop saf for each populatoin

# or you can find the 2dim sf by
# ./realSFS ceu-sfs1.saf.idx yri-sfs1.saf.idx
# NB the program will find the intersect internally. No need for multiple runs with angsd main program.
# 
# or you can find the 3dim sf by
# ./realSFS ceu-sfs1.saf.idx yri-sfs1.saf.idx MEX-sfs1.saf.idx
# 

# * NB the ancestral state needs to be supplied for the full SFS, but you can use the -fold 1 to estimate the folded SFS and then use the reference as ancestral.
# * NB the output from the -doSaf 2 are not sample allele frequency likelihoods but sample alle posteriors.
# And applying the realSFS to this output is therefore NOT the ML estimate of the SFS as described in the Nielsen 2012 paper,
# but the 'Incorporating deviations from Hardy-Weinberg Equilibrium (HWE)' section of that paper.
# 
# CURRENTLY: arg, beagle.gz, cov, inbreed, qopt, mafs.gz, selecton.gz
# 
# 
# Our program can estimate fst between populations. And has been generalized to give all pairwise fst estimates if you supply the command with multiple populations.
# 
# if you supply 3 populations, the program will also output the pbs statistic.
# NB we have removed the very unusefull unweighted fst estimator in the output, and have included a header. The output example below will be updated at some point.
# The procedure is
# 
# - Use angsd for calculating saf files for each population
# 
# 
# 
# 
# 
# - Use realSFS to calculate 2d sfs for each pair
# 
# - Use the above calculated 2dsfs as priors jointly with all safs from step1 to calculate fst binary files
# 
# - Use realSFS to extract the the fst values from the fst
# 
# NB; In the latest github version there is a different fst estimator which should be preferable for small sample sizes. Feel free to try that out with
# 
# this is with 2pops
# first calculate per pop saf for each populatoin
# ../angsd -b list1  -anc hg19ancNoChr.fa -out pop1 -dosaf 1 -gl 1
# ../angsd -b list2  -anc hg19ancNoChr.fa -out pop2 -dosaf 1 -gl 1
# calculate the 2dsfs prior
# ../misc/realSFS pop1-sfs1.saf.idx pop2-sfs1.saf.idx >pop1.pop2.ml
# prepare the fst for easy window analysis etc
# ../misc/realSFS fst index pop1-sfs1.saf.idx pop2-sfs1.saf.idx -sfs pop1.pop2.ml -fstout here
# get the global estimate
# ../misc/realSFS fst stats here.fst.idx 
# -> FST.Unweight:0.069395 Fst.Weight:0.042349
# below is not tested that much, but seems to work
# ../misc/realSFS fst stats2 here.fst.idx -win 50000 -step 10000 >slidingwindow