#!/bin/bash
#PBS -l select=1:ncpus=64
#PBS -l walltime=5000:00:00
#PBS -N GATK_SNP_GVCF
#PBS -j oe
#PBS -m ae
#PBS -M lmoreira@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence

echo
echo
echo Combine GVCFs
echo
echo

time java -jar /home/lmoreira/programs/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar \
-T GenotypeGVCFs \
-R $ref \
--variant PV-NW-8.recal.raw.g.vcf \
--variant PV-NW-16.recal.raw.g.vcf \
--variant PV-NW-17.recal.raw.g.vcf \
--variant PV-NW-18.recal.raw.g.vcf \
--variant PV-NW-21.recal.raw.g.vcf \
--variant PV-NW-23.recal.raw.g.vcf \
--variant PV-NW-25.recal.raw.g.vcf \
--variant PV-NW-26.recal.raw.g.vcf \
--variant PV-NW-27.recal.raw.g.vcf \
-o allsamples.recal.raw.vcf \
-nt 64
