#!/bin/bash
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N reformat
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH


date
time

module load bwa-0.7.15
module load fastqc-0.11.5
module load R-3.4.1

for i in /home/kprovost/nas3/genomeresequencingFromLucas/*chrom*/*fasta; do 
time bwa index -a bwtsw $i
time /home/kprovost/nas3/samtools/samtools faidx $i
java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar CreateSequenceDictionary \
    REFERENCE=$i \ 
    OUTPUT=$i.dict
done
