#!/bin/bash
#PBS -l select=1:ncpus=32
#PBS -l walltime=5000:00:00
#PBS -N bel75_dxy
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## bam_list = list of BAM files
## the indlists for son and chi work for this
bamlist=/home/kprovost/nas3/ANGSD_pipeline/Vireo_bellii_75.bamlist
sonlist=/home/kprovost/nas3/ANGSD_pipeline/SON_Vireo_bellii_75.indlist
chilist=/home/kprovost/nas3/ANGSD_pipeline/CHI_Vireo_bellii_75.indlist

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

date
time

if [ ! -f "Vireo_bellii_75-DXY.mafs" ]; then
time /home/kprovost/nas3/angsd/angsd -GL 2 \
-doMajorMinor 1 \
-doMaf 3 \
-doGlf 2 \
-minMaf 0.05 \
-SNP_pval 0.01 \
-skipTriallelic \
-minInd 4 \
-minMapQ 20 \
-minQ 20 \
-nThreads 32 \
-bam $bamlist \
-out Vireo_bellii_75-DXY
gunzip -f Vireo_bellii_75-DXY.mafs.gz
fi

if [ ! -f "Vireo_bellii_75_SON-DXY.mafs" ]; then
time /home/kprovost/nas3/angsd/angsd -GL 2 \
-doMajorMinor 1 \
-doMaf 3 \
-doGlf 2 \
-minMaf 0.05 \
-SNP_pval 0.01 \
-skipTriallelic \
-minInd 4 \
-minMapQ 20 \
-minQ 20 \
-nThreads 32 \
-bam $sonlist \
-out Vireo_bellii_75_SON-DXY
gunzip -f Vireo_bellii_75_SON-DXY.mafs.gz
fi

if [ ! -f "Vireo_bellii_75_CHI-DXY.mafs" ]; then
time /home/kprovost/nas3/angsd/angsd -GL 2 \
-doMajorMinor 1 \
-doMaf 3 \
-doGlf 2 \
-minMaf 0.05 \
-SNP_pval 0.01 \
-skipTriallelic \
-minInd 4 \
-minMapQ 20 \
-minQ 20 \
-nThreads 32 \
-bam $chilist \
-out Vireo_bellii_75_CHI-DXY
gunzip -f Vireo_bellii_75_CHI-DXY.mafs.gz
fi

