#!/bin/bash
#PBS -l select=1:ncpus=2
#PBS -l walltime=5000:00:00
#PBS -N S5.1_unfiltered
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## vcf
cd /vz-nas1-active/RawGenomicReads/FASTQ_SCREEN_RESULTS/Parrots/BAM_dedup/vcf_files
vcf=allsamples.raw-MISSING-B6-C5.vcf

echo
echo "#######################"
echo $vcf
echo "#######################"

echo
echo
echo Selecting Variants 
echo
echo

## REMOVED:
#--min-alleles 2 --max-alleles 2 ## this forces bi-allelic. since this is across species, not picking that 

## not changed from previous
/home/kprovost/opt/bin/vcftools \
--vcf $vcf \
--remove-indels \
--remove-filtered-all \
--min-meanDP 2 \
--max-meanDP 100 \
--max-maf 0.05 \
--max-missing 0.25 \
--hwe 0.01 \
--recode \
--recode-INFO-all \
--out allsamples.raw-MISSING-B6-C5_maf0.05_missing0.25

echo
echo
echo Selecting Variants
echo
echo

## not different 
/home/kprovost/opt/bin/vcftools \
--vcf $vcf \
--remove-indels \
--remove-filtered-all \
--min-meanDP 2 \
--max-meanDP 100 \
--max-maf 0.02 \
--max-missing 0.25 \
--hwe 0.01 \
--recode \
--recode-INFO-all \
--out allsamples.raw-MISSING-B6-C5_maf0.02_missing0.25

echo
echo
echo Selecting Variants
echo
echo

## didn't change
/home/kprovost/opt/bin/vcftools \
--vcf $vcf \
--remove-indels \
--remove-filtered-all \
--min-meanDP 2 \
--max-meanDP 100 \
--max-missing 0.25 \
--hwe 0.01 \
--recode \
--recode-INFO-all \
--out allsamples.raw-MISSING-B6-C5_missing0.25

