#!/bin/bash
#PBS -l select=1:ncpus=2:mem=128gb
#PBS -l walltime=99999:00:00
#PBS -N bel_sfs2
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Corv_chrom/pseudochromosomesSHORT.fasta

##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo

## bam_list = list of BAM files
sonlist=/home/kprovost/nas3/ANGSD_pipeline/SON_Vireo_bellii.indlist
chilist=/home/kprovost/nas3/ANGSD_pipeline/CHI_Vireo_bellii.indlist

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

rm bel_sfs2.logfile


date >> bel_sfs2.logfile 2>&1
time >> bel_sfs2.logfile 2>&1

## get the global sfs
# echo "GLOBAL SFS" >> bel_sfs2.logfile 2>&1
# time /home/kprovost/nas3/angsd/misc/realSFS -nSites 50000000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/Vireo-bellii-sfs1.saf.idx >> bel_sfs2.logfile 2>&1

## get the by population sfs 
# echo >> bel_sfs2.logfile 2>&1
# echo "SON SFS"  >> bel_sfs2.logfile 2>&1
# /home/kprovost/nas3/angsd/angsd -b $sonlist \
# -anc $ref \
# -out SON_Vireo_bellii-sfs1 \
# -dosaf 1 \
# -gl 1 >> bel_sfs2.logfile 2>&1

# echo >> bel_sfs2.logfile 2>&1
# echo "CHI SFS" >> bel_sfs2.logfile 2>&1
# /home/kprovost/nas3/angsd/angsd -b $chilist \
# -anc $ref \
# -out CHI_Vireo_bellii-sfs1 \
# -dosaf 1 \
# -gl 1 >> bel_sfs2.logfile 2>&1

## now get the 2d sfs for each 
command="time /home/kprovost/nas3/angsd/misc/realSFS -nSites 50000000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Vireo_bellii-sfs1.saf.idx /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Vireo_bellii-sfs1.saf.idx > SON_CHI_Vireo_bellii.ml"
eval $command >> bel_sfs2.logfile 2>&1
