#!/bin/bash
#PBS -l select=1:ncpus=32:mem=128gb
#PBS -l walltime=99999:00:00
#PBS -N fla-NOWEIRD_sfs2
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Paru_chrom/pseudochromosomesSHORT.fasta

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

sonlistMIN1A=/home/kprovost/nas3/ANGSD_pipeline/SON_Auriparus_flaviceps-NOWEIRD.indlistMIN1A
sonlistMIN1B=/home/kprovost/nas3/ANGSD_pipeline/SON_Auriparus_flaviceps-NOWEIRD.indlistMIN1B
sonlistMIN1C=/home/kprovost/nas3/ANGSD_pipeline/SON_Auriparus_flaviceps-NOWEIRD.indlistMIN1C
sonlistMIN1D=/home/kprovost/nas3/ANGSD_pipeline/SON_Auriparus_flaviceps-NOWEIRD.indlistMIN1D

# echo >> fla-NOWEIRD_sfs2_SONMIN1A.logfileMIN1A 2>&1
# echo "SON SFS" >> fla-NOWEIRD_sfs2_SONMIN1A.logfileMIN1A 2>&1
# /home/kprovost/nas3/angsd/angsd -b $sonlistMIN1A \
# -anc $ref \
# -out SONMIN1A_Auriparus_flaviceps-NOWEIRD-sfs1 \
# -dosaf 1 \
# -gl 1 >> fla-NOWEIRD_sfs2_SONMIN1A.logfileMIN1A 2>&1

# echo >> fla-NOWEIRD_sfs2_SONMIN1B.logfileMIN1B 2>&1
# echo "SON SFS" >> fla-NOWEIRD_sfs2_SONMIN1B.logfileMIN1B 2>&1
# /home/kprovost/nas3/angsd/angsd -b $sonlistMIN1B \
# -anc $ref \
# -out SONMIN1B_Auriparus_flaviceps-NOWEIRD-sfs1 \
# -dosaf 1 \
# -gl 1 >> fla-NOWEIRD_sfs2_SONMIN1B.logfileMIN1B 2>&1

# echo >> fla-NOWEIRD_sfs2_SONMIN1C.logfileMIN1C 2>&1
# echo "SON SFS" >> fla-NOWEIRD_sfs2_SONMIN1C.logfileMIN1C 2>&1
# /home/kprovost/nas3/angsd/angsd -b $sonlistMIN1C \
# -anc $ref \
# -out SONMIN1C_Auriparus_flaviceps-NOWEIRD-sfs1 \
# -dosaf 1 \
# -gl 1 >> fla-NOWEIRD_sfs2_SONMIN1C.logfileMIN1C 2>&1

echo >> fla-NOWEIRD_sfs2_SONMIN1D.logfileMIN1D 2>&1
echo "SON SFS" >> fla-NOWEIRD_sfs2_SONMIN1D.logfileMIN1D 2>&1
/home/kprovost/nas3/angsd/angsd -b $sonlistMIN1D \
-anc $ref \
-out SONMIN1D_Auriparus_flaviceps-NOWEIRD-sfs1 \
-dosaf 1 \
-gl 1 >> fla-NOWEIRD_sfs2_SONMIN1D.logfileMIN1D 2>&1


mv /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/*fla*saf* /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/

# command="time /home/kprovost/nas3/angsd/misc/realSFS \
# -nSites 50000000 \
# /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SONMIN1A_Auriparus_flaviceps-NOWEIRD-sfs1.saf.idx \
# /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Auriparus_flaviceps-NOWEIRD-sfs1.saf.idx \
# > SONMIN1A_CHI1_Auriparus_flaviceps-NOWEIRD.ml.MIN1A"
# eval $command >> fla-NOWEIRD_sfs2.logfileMIN1A 2>&1

# command="time /home/kprovost/nas3/angsd/misc/realSFS \
# -nSites 50000000 \
# /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SONMIN1B_Auriparus_flaviceps-NOWEIRD-sfs1.saf.idx \
# /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Auriparus_flaviceps-NOWEIRD-sfs1.saf.idx \
# > SONMIN1B_CHI1_Auriparus_flaviceps-NOWEIRD.ml.MIN1B"
# eval $command >> fla-NOWEIRD_sfs2.logfileMIN1B 2>&1

# command="time /home/kprovost/nas3/angsd/misc/realSFS \
# -nSites 50000000 \
# /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SONMIN1C_Auriparus_flaviceps-NOWEIRD-sfs1.saf.idx \
# /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Auriparus_flaviceps-NOWEIRD-sfs1.saf.idx \
# > SONMIN1C_CHI1_Auriparus_flaviceps-NOWEIRD.ml.MIN1C"
# eval $command >> fla-NOWEIRD_sfs2.logfileMIN1C 2>&1

command="time /home/kprovost/nas3/angsd/misc/realSFS \
-nSites 50000000 \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SONMIN1D_Auriparus_flaviceps-NOWEIRD-sfs1.saf.idx \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Auriparus_flaviceps-NOWEIRD-sfs1.saf.idx \
> SONMIN1D_CHI1_Auriparus_flaviceps-NOWEIRD.ml.MIN1D"
eval $command >> fla-NOWEIRD_sfs2.logfileMIN1D 2>&1
