#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=99999:00:00
#PBS -N S5.2_vcfstats
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

## arguemnts:
## vcf 

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/

export PERL5LIB=$PERL5LIB:/home/kprovost/nas3/vcftools/src/perl
export PERL5LIB=$PERL5LIB:/usr/bin/perl
export PERL5LIB=$PERL5LIB:/usr/lib64/perl5/vendor_perl/
export PERL5LIB=$PERL5LIB:/usr/lib64/perl5/vendor_perl/Data

echo
echo "#######################"
echo $vcf
echo "#######################"

/home/kprovost/nas3/vcftools/bin/vcf-stats $vcf > ${vcf}.stats

