#!/bin/bash
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N sfsbel
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH
##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/
## original nsites was 5000000
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/SON_Vireo_bellii_75.sfs1.saf.idx > SON_Vireo_bellii_75.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/CHI_Vireo_bellii_75.sfs1.saf.idx > CHI_Vireo_bellii_75.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/CHI_Vireo_bellii_50.sfs1.saf.idx > CHI_Vireo_bellii_50.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/SON_Vireo_bellii_50.sfs1.saf.idx > SON_Vireo_bellii_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/CHI_Vireo_bellii_100.sfs1.saf.idx > CHI_Vireo_bellii_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/CHI_Vireo_bellii.sfs1.saf.idx > CHI_Vireo_bellii_X.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/CHI_Vireo-bellii_100.taj1.saf.idx > CHI_Vireo_bellii_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/Vireo-bellii-CHI-taj1.saf.idx > CHI_Vireo_bellii_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/Vireo-bellii-NOWEIRD-CHI-taj1.saf.idx > CHI_Vireo_bellii_NOWEIRD_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/SON_Vireo_bellii_100.sfs1.saf.idx > SON_Vireo_bellii_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/SON_Vireo_bellii.sfs1.saf.idx > SON_Vireo_bellii_X.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/SON_Vireo-bellii_100.taj1.saf.idx > SON_Vireo_bellii_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/Vireo-bellii-NOWEIRD-SON-taj1.saf.idx > SON_Vireo_bellii_NOWEIRD_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/Vireo-bellii-SON-taj1.saf.idx > SON_Vireo_bellii_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/Vireo_bellii_100.sfs1.saf.idx > Vireo_bellii_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/Vireo-bellii_100.taj1.saf.idx > Vireo_bellii_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/Vireo-bellii-NOWEIRD-taj1.saf.idx > Vireo_bellii_NOWEIRD_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/Vireo-bellii-sfs1.saf.idx > Vireo_bellii.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel/Vireo-bellii-taj1.saf.idx > Vireo_bellii_taj.ml
