#!/bin/bash
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N sfsmel
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH
##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/
## original nsites was 5000000
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/SON_Polioptila_melanura_75.sfs1.saf.idx > SON_Polioptila_melanura_75.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/CHI_Polioptila_melanura_50.sfs1.saf.idx > CHI_Polioptila_melanura_50.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/CHI_Polioptila_melanura_75.sfs1.saf.idx > CHI_Polioptila_melanura_75.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/SON_Polioptila_melanura_50.sfs1.saf.idx > SON_Polioptila_melanura_50.ml
# time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/CHI_Polioptila_melanura_100.sfs1.saf.idx > CHI_Polioptila_melanura_100.ml
# time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/CHI_Polioptila_melanura.sfs1.saf.idx > CHI_Polioptila_melanura.ml
# time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/CHI_Polioptila-melanura_100.taj1.saf.idx > CHI_Polioptila_melanura_taj_100.ml
# time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/CHI_Polioptila-melanura-NOWEIRD_100.taj1.saf.idx > CHI_Polioptila_melanura_NOWEIRD_taj_100.ml
# time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/Polioptila-melanura-CHI-taj1.saf.idx > CHI_Polioptila_melanura_taj.ml

time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/Polioptila_melanura-sfs1.saf.idx > Polioptila_melanura.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/Polioptila-melanura_100.taj1.saf.idx > Polioptila_melanura_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/Polioptila-melanura-NOWEIRD_100.taj1.saf.idx > Polioptila_melanura_NOWEIRD_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/Polioptila-melanura-taj1.saf.idx > Polioptila_melanura_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/Polioptila-melanura-SON-taj1.saf.idx > SON_Polioptila_melanura_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/SON_Polioptila_melanura_100.sfs1.saf.idx > SON_Polioptila_melanura_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/SON_Polioptila_melanura.sfs1.saf.idx > SON_Polioptila_melanura.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/SON_Polioptila-melanura_100.taj1.saf.idx > SON_Polioptila_melanura_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/SON_Polioptila-melanura-NOWEIRD_100.taj1.saf.idx > SON_Polioptila_melanura_NOWEIRD_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/mel/Polioptila_melanura_100.sfs1.saf.idx > Polioptila_melanura_100.ml
