#!/bin/bash
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N sfscur
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH
##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/
## original nsites was 5000000
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/SON_Toxostoma_curvirostre_75.sfs1.saf.idx > SON_Toxostoma_curvirostre_75.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/CHI_Toxostoma_curvirostre_75.sfs1.saf.idx > CHI_Toxostoma_curvirostre_75.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/CHI_Toxostoma_curvirostre_50.sfs1.saf.idx > CHI_Toxostoma_curvirostre_50.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/SON_Toxostoma_curvirostre_50.sfs1.saf.idx > SON_Toxostoma_curvirostre_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/CHI_Toxostoma_curvirostre_100.sfs1.saf.idx > CHI_Toxostoma_curvirostre_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/CHI_Toxostoma_curvirostre.sfs1.saf.idx > CHI_Toxostoma_curvirostre.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/CHI_Toxostoma-curvirostre_100.taj1.saf.idx > CHI_Toxostoma_curvirostre_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/Toxostoma-curvirostre-CHI-taj1.saf.idx > CHI_Toxostoma_curvirostre_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/SON_Toxostoma_curvirostre_100.sfs1.saf.idx > SON_Toxostoma_curvirostre_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/SON_Toxostoma_curvirostre.sfs1.saf.idx > SON_Toxostoma_curvirostre.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/SON_Toxostoma-curvirostre_100.taj1.saf.idx > SON_Toxostoma_curvirostre_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/Toxostoma-curvirostre-SON-taj1.saf.idx > SON_Toxostoma_curvirostre_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/Toxostoma_curvirostre_100.sfs1.saf.idx > Toxostoma_curvirostre_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/Toxostoma_curvirostre-sfs1.saf.idx > Toxostoma_curvirostre.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/Toxostoma-curvirostre_100.taj1.saf.idx > Toxostoma_curvirostre_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/cur/Toxostoma-curvirostre-taj1.saf.idx > Toxostoma_curvirostre_taj.ml
