#!/bin/bash
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N sfsfus
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH
##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/
## original nsites was 5000000
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/CHI_Melozone_fusca_50.sfs1.saf.idx > CHI_Melozone_fusca_50.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/CHI_Melozone_fusca_75.sfs1.saf.idx > CHI_Melozone_fusca_75.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/SON_Melozone_fusca_50.sfs1.saf.idx > SON_Melozone_fusca_50.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/SON_Melozone_fusca_75.sfs1.saf.idx > SON_Melozone_fusca_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/CHI_Melozone_fusca_100.sfs1.saf.idx" > CHI_Melozone_fusca_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/CHI_Melozone_fusca.sfs1.saf.idx" > CHI_Melozone_fusca.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/CHI_Melozone-fusca_100.taj1.saf.idx" > CHI_Melozone_fusca_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/Melozone-fusca-CHI-taj1.saf (1).idx" > CHI_Melozone_fusca_tajX.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/Melozone-fusca-CHI-taj1.saf.idx" > CHI_Melozone_fusca_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/Melozone_fusca_100.sfs1.saf.idx" > Melozone_fusca_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/Melozone-fusca_100.taj1.saf.idx" > Melozone_fusca_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/Melozone-fusca-taj1.saf (1).idx" > Melozone_fusca_tajX.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/Melozone-fusca-taj1.saf.idx" > Melozone_fusca_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/SON_Melozone_fusca_100.sfs1.saf.idx" > SON_Melozone_fusca_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/SON_Melozone_fusca.sfs1.saf.idx" > SON_Melozone_fusca.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/SON_Melozone-fusca_100.taj1.saf.idx" > SON_Melozone_fusca_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/Melozone-fusca-SON-taj1.saf (1).idx" > SON_Melozone_fusca_tajX.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fus/Melozone-fusca-SON-taj1.saf.idx" > SON_Melozone_fusca_taj.ml
