#!/bin/bash
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N sfsbru
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH
##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/
## original nsites was 5000000
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/SON_Campylorhynchus_brunneicapillus_75.sfs1.saf.idx > SON_Campylorhynchus_brunneicapillus_75.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/CHI_Campylorhynchus_brunneicapillus_75.sfs1.saf.idx > CHI_Campylorhynchus_brunneicapillus_75.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/CHI_Campylorhynchus_brunneicapillus_50.sfs1.saf.idx > CHI_Campylorhynchus_brunneicapillus_50.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/SON_Campylorhynchus_brunneicapillus_50.sfs1.saf.idx > SON_Campylorhynchus_brunneicapillus_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/Campylorhynchus_brunneicapillus_100.sfs1.saf.idx > Campylorhynchus_brunneicapillus_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/Campylorhynchus-brunneicapillus_100.taj1.saf.idx > Campylorhynchus_brunneicapillus_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/Campylorhynchus-brunneicapillus-taj1.saf.idx > Campylorhynchus_brunneicapillus_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/Campylorhynchus-brunneicapillus-CHI-taj1.saf.idx > CHI_Campylorhynchus_brunneicapillus_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/Campylorhynchus-brunneicapillus-NOWEIRD-CHI-taj1.saf.idx > CHI_Campylorhynchus_brunneicapillus_NOWEIRD_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/CHI_Campylorhynchus_brunneicapillus_100.sfs1.saf.idx > CHI_Campylorhynchus_brunneicapillus_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/CHI_Campylorhynchus_brunneicapillus.sfs1.saf.idx > CHI_Campylorhynchus_brunneicapillus_X.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/CHI_Campylorhynchus-brunneicapillus_100.taj1.saf.idx > CHI_Campylorhynchus_brunneicapillus_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/Campylorhynchus-brunneicapillus-SON-taj1.saf.idx > SON_Campylorhynchus_brunneicapillus_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/Campylorhynchus-brunneicapillus-NOWEIRD-SON-taj1.saf.idx > SON_Campylorhynchus_brunneicapillus_NOWEIRD_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/SON_Campylorhynchus_brunneicapillus_100.sfs1.saf.idx > SON_Campylorhynchus_brunneicapillus_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/SON_Campylorhynchus_brunneicapillus.sfs1.saf.idx > SON_Campylorhynchus_brunneicapillus_X.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bru/SON_Campylorhynchus-brunneicapillus_100.taj1.saf.idx > SON_Campylorhynchus_brunneicapillus_taj_100.ml
