#!/bin/bash
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N sfs
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

## original nsites was 5000000
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Amphispiza-bilineata_75.sfs1.saf.idx > SON_Amphispiza-bilineata_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Auriparus-flaviceps_75.sfs1.saf.idx > SON_Auriparus-flaviceps_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Campylorhynchus-brunneicapillus_75.sfs1.saf.idx > SON_Campylorhynchus-brunneicapillus_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Cardinalis-sinuatus_75.sfs1.saf.idx > SON_Cardinalis-sinuatus_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Melozone-fusca_75.sfs1.saf.idx > SON_Melozone-fusca_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Phainopepla-nitens_75.sfs1.saf.idx > SON_Phainopepla-nitens_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Polioptila-melanura_75.sfs1.saf.idx > SON_Polioptila-melanura_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Toxostoma-crissale_75.sfs1.saf.idx > SON_Toxostoma-crissale_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Toxostoma-curvirostre_75.sfs1.saf.idx > SON_Toxostoma-curvirostre_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Vireo-bellii_75.sfs1.saf.idx > SON_Vireo-bellii_75.ml

time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Amphispiza-bilineata_75.sfs1.saf.idx > CHI_Amphispiza-bilineata_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Auriparus-flaviceps_75.sfs1.saf.idx > CHI_Auriparus-flaviceps_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Campylorhynchus-brunneicapillus_75.sfs1.saf.idx > CHI_Campylorhynchus-brunneicapillus_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Cardinalis-sinuatus_75.sfs1.saf.idx > CHI_Cardinalis-sinuatus_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Melozone-fusca_75.sfs1.saf.idx > CHI_Melozone-fusca_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Phainopepla-nitens_75.sfs1.saf.idx > CHI_Phainopepla-nitens_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Polioptila-melanura_75.sfs1.saf.idx > CHI_Polioptila-melanura_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Toxostoma-crissale_75.sfs1.saf.idx > CHI_Toxostoma-crissale_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Toxostoma-curvirostre_75.sfs1.saf.idx > CHI_Toxostoma-curvirostre_75.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Vireo-bellii_75.sfs1.saf.idx > CHI_Vireo-bellii_75.ml

time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Amphispiza-bilineata_50.sfs1.saf.idx > CHI_Amphispiza-bilineata_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Auriparus-flaviceps_50.sfs1.saf.idx > CHI_Auriparus-flaviceps_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Campylorhynchus-brunneicapillus_50.sfs1.saf.idx > CHI_Campylorhynchus-brunneicapillus_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Cardinalis-sinuatus_50.sfs1.saf.idx > CHI_Cardinalis-sinuatus_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Melozone-fusca_50.sfs1.saf.idx > CHI_Melozone-fusca_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Phainopepla-nitens_50.sfs1.saf.idx > CHI_Phainopepla-nitens_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Polioptila-melanura_50.sfs1.saf.idx > CHI_Polioptila-melanura_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Toxostoma-crissale_50.sfs1.saf.idx > CHI_Toxostoma-crissale_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Toxostoma-curvirostre_50.sfs1.saf.idx > CHI_Toxostoma-curvirostre_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Vireo-bellii_50.sfs1.saf.idx > CHI_Vireo-bellii_50.ml

time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Amphispiza-bilineata_50.sfs1.saf.idx > SON_Amphispiza-bilineata_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Auriparus-flaviceps_50.sfs1.saf.idx > SON_Auriparus-flaviceps_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Campylorhynchus-brunneicapillus_50.sfs1.saf.idx > SON_Campylorhynchus-brunneicapillus_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Cardinalis-sinuatus_50.sfs1.saf.idx > SON_Cardinalis-sinuatus_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Melozone-fusca_50.sfs1.saf.idx > SON_Melozone-fusca_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Phainopepla-nitens_50.sfs1.saf.idx > SON_Phainopepla-nitens_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Polioptila-melanura_50.sfs1.saf.idx > SON_Polioptila-melanura_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Toxostoma-crissale_50.sfs1.saf.idx > SON_Toxostoma-crissale_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Toxostoma-curvirostre_50.sfs1.saf.idx > SON_Toxostoma-curvirostre_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Vireo-bellii_50.sfs1.saf.idx > SON_Vireo-bellii_50.ml

time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Amphispiza-bilineata_100.sfs1.saf.idx > CHI_Amphispiza-bilineata.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Auriparus-flaviceps_100.sfs1.saf.idx > CHI_Auriparus-flaviceps.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Campylorhynchus-brunneicapillus_100.sfs1.saf.idx > CHI_Campylorhynchus-brunneicapillus.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Cardinalis-sinuatus_100.sfs1.saf.idx > CHI_Cardinalis-sinuatus.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Melozone-fusca_100.sfs1.saf.idx > CHI_Melozone-fusca.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Phainopepla-nitens_100.sfs1.saf.idx > CHI_Phainopepla-nitens.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Polioptila-melanura_100.sfs1.saf.idx > CHI_Polioptila-melanura.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Toxostoma-crissale_100.sfs1.saf.idx > CHI_Toxostoma-crissale.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Toxostoma-curvirostre_100.sfs1.saf.idx > CHI_Toxostoma-curvirostre.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Vireo-bellii_100.sfs1.saf.idx > CHI_Vireo-bellii.ml

time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Amphispiza-bilineata_100.sfs1.saf.idx > SON_Amphispiza-bilineata.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Auriparus-flaviceps_100.sfs1.saf.idx > SON_Auriparus-flaviceps.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Campylorhynchus-brunneicapillus_100.sfs1.saf.idx > SON_Campylorhynchus-brunneicapillus.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Cardinalis-sinuatus_100.sfs1.saf.idx > SON_Cardinalis-sinuatus.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Melozone-fusca_100.sfs1.saf.idx > SON_Melozone-fusca.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Phainopepla-nitens_100.sfs1.saf.idx > SON_Phainopepla-nitens.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Polioptila-melanura_100.sfs1.saf.idx > SON_Polioptila-melanura.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Toxostoma-crissale_100.sfs1.saf.idx > SON_Toxostoma-crissale.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Toxostoma-curvirostre_100.sfs1.saf.idx > SON_Toxostoma-curvirostre.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Vireo-bellii_100.sfs1.saf.idx > SON_Vireo-bellii.ml
