#!/bin/bash
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N sfsfla
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH
##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/
## original nsites was 5000000
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/SON_Auriparus_flaviceps_75.sfs1.saf.idx > SON_Auriparus_flaviceps_75.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/CHI_Auriparus_flaviceps_75.sfs1.saf.idx > CHI_Auriparus_flaviceps_75.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/CHI_Auriparus_flaviceps_50.sfs1.saf.idx > CHI_Auriparus_flaviceps_50.ml
#time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/SON_Auriparus_flaviceps_50.sfs1.saf.idx > SON_Auriparus_flaviceps_50.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/Auriparus_flaviceps_100.sfs1.saf.idx > Auriparus_flaviceps_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/Auriparus-flaviceps_100.taj1.saf.idx > Auriparus_flaviceps_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/Auriparus-flaviceps-NOWEIRD_100.taj1.saf.idx > Auriparus_flaviceps_NOWEIRD_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/Auriparus-flaviceps-taj1.saf.idx > Auriparus_flaviceps_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/Auriparus-flaviceps-CHI-taj1.saf.idx > CHI_Auriparus_flaviceps_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/Auriparus-flaviceps-NOWEIRD-CHI-taj1.saf.idx > CHI_Auriparus_flaviceps_NOWERD_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/CHI_Auriparus_flaviceps_100.sfs1.saf.idx > CHI_Auriparus_flaviceps_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/CHI_Auriparus-flaviceps_100.taj1.saf.idx > CHI_Auriparus_flaviceps_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/CHI_Auriparus-flaviceps-NOWEIRD_100.taj1.saf.idx > CHI_Auriparus_flaviceps_NOWEIRD_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/Auriparus-flaviceps-NOWEIRD-SON-taj1.saf.idx > SON_Auriparus_flaviceps_NOWEIRD_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/Auriparus-flaviceps-SON-taj1.saf.idx > SON_Auriparus_flaviceps_taj.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/SON_Auriparus_flaviceps_100.sfs1.saf.idx > SON_Auriparus_flaviceps_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/SON_Auriparus-flaviceps_100.taj1.saf.idx > SON_Auriparus_flaviceps_taj_100.ml
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 100000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/fla/SON_Auriparus-flaviceps-NOWEIRD_100.taj1.saf.idx > SON_Auriparus_flaviceps_NOWEIRD_taj_100.ml
