#!/bin/bash
#PBS -l select=1:ncpus=32
#PBS -l walltime=5000:00:00
#PBS -N all2_PCAngsd
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#run=1
run=2
#run=3

#spp="Vireo-bellii"
#spp="Amphispiza-bilineata"
#spp="Campylorhynchus-brunneicapillus"
#spp="Toxostoma-crissale"
#spp="Toxostoma-curvirostre"
#spp="Auriparus-flaviceps"
#spp="Melozone-fusca"
#spp="Polioptila-melanura"
#spp="Phainopepla-nitens"
spp="Cardinalis-sinuatus"

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

#Arguments:
## GL = genotype likehood file (Beagle format)


#Declare a string array
spplist=( "Vireo-bellii" "Amphispiza-bilineata" "Campylorhynchus-brunneicapillus" "Toxostoma-crissale" "Toxostoma-curvirostre" "Auriparus-flaviceps" "Melozone-fusca" "Polioptila-melanura" "Phainopepla-nitens" "Cardinalis-sinuatus" "Campylorhynchus-brunneicapillus-NOWEIRD" "Phainopepla-nitens-NOWEIRD" "Polioptila-melanura-NOWEIRD" "Vireo-bellii-NOWEIRD")
 
# Print array values in  lines
for spp in ${spplist[*]}; do
echo $spp

#source activate py36
for GLu in ./BEAGLE/${spp}/*F.beagle; do 
#echo $GLu
gzip -f $GLu
done;
for GLu in ./BEAGLE/*beagle; do 
#echo $GLu
gzip -f $GLu
done;

if [[ "$run" == 1 ]]; then
for GL in ./BEAGLE/${spp}/*.F.beagle.gz; do
echo "###################"
echo $GL
outname=${GL%.beagle.gz}
outname=${outname#./BEAGLE/$spp/}
echo $outname
for k in {1..4}; do ## this does 2-5
echo $k
#if [ ! -f ./QOPTS/${outname}.${spp}_PCAngsd.${k}*qopt ]; then
#if [ ! -f ${outname}.${spp}_PCAngsd.${k}*qopt ]; then 
if [ ! -f ${outname}.${spp}_PCAngsd.$k.admix.Q.npy ]; then 
if [ ! -f ./QOPTS/${outname}.${spp}_PCAngsd.$k.admix.Q.npy ]; then 
# Estimate covariance matrix and individual admixture proportions
echo "RUN"
date
time
python2.7 /home/kprovost/nas3/pcangsd/pcangsd.py \
-beagle $GL \
-admix -admix_save -e $k \
-inbreed 2 \
-selection -sites_save \
-o ${outname}.${spp}_PCAngsd.$k \
 -threads 32 > ${outname}.${spp}_pca.$k.log 2>&1
else
echo "ALREADY HERE1"
fi 
else
echo "ALREADY HERE2"
fi 
mv *selection* ./SELECTIONS/
mv *qopt* ./QOPTS/
mv *fopt* ./FOPTS/
mv *admix.F* ./FOPTS/
mv *admix.Q* ./QOPTS/
mv *cov* ./COV_INBREED/
mv *inbreed* ./COV_INBREED/
mv *sites* ./PCASITES/
mv *log* ./LOGS/
done
done
fi

if [[ "$run" == 2 ]]; then
for GL in ./BEAGLE/*${spp}*.beagle.gz; do
echo "###################"
echo $GL
outname=${GL%.beagle.gz}
outname=${outname#./BEAGLE/$spp/}
echo $outname
for k in {1..4}; do
echo $k
#if [ ! -f ./QOPTS/${outname}.${spp}_PCAngsd.${k}*qopt ]; then
#if [ ! -f ${outname}.${spp}_PCAngsd.${k}*qopt ]; then 
if [ ! -f ${outname}.${spp}_PCAngsd.$k.admix.Q.npy ]; then 
if [ ! -f ./QOPTS/${outname}.${spp}_PCAngsd.$k.admix.Q.npy ]; then 
# Estimate covariance matrix and individual admixture proportions
echo "RUN"
date
time
python3 /home/kprovost/nas3/pcangsd/pcangsd.py \
-beagle $GL \
-admix -admix_save -e $k \
-inbreed 2 \
-selection -sites_save \
-o ${outname}.${spp}_PCAngsd.$k \
 -threads 32 > ${outname}.${spp}_pca.$k.log 2>&1
## note old version of pcangsd had "selection -1"
else
echo "ALREADY HERE1"
fi 
else
echo "ALREADY HERE2"
fi 
mv ./BEAGLE/*selection* ./SELECTIONS/
mv ./BEAGLE/*qopt* ./QOPTS/
mv ./BEAGLE/*fopt* ./FOPTS/
mv ./BEAGLE/*admix.F* ./FOPTS/
mv ./BEAGLE/*admix.Q* ./QOPTS/
mv ./BEAGLE/*cov* ./COV_INBREED/
mv ./BEAGLE/*inbreed* ./COV_INBREED/
mv ./BEAGLE/*sites* ./PCASITES/
mv ./BEAGLE/*log* ./LOGS/
done
done
fi

if [[ "$run" == 3 ]]; then
for GL in ./BEAGLE/${spp}/*.beagle.gz; do
echo "###################"
echo $GL
outname=${GL%.beagle.gz}
outname=${outname#./BEAGLE/$spp/}
echo $outname
for k in {1..4}; do
echo $k
#if [ ! -f ./QOPTS/${outname}.${spp}_PCAngsd.${k}*qopt ]; then
#if [ ! -f ${outname}.${spp}_PCAngsd.${k}*qopt ]; then 
if [ ! -f ${outname}.${spp}_PCAngsd.$k.admix.Q.npy ]; then 
if [ ! -f ./QOPTS/${outname}.${spp}_PCAngsd.$k.admix.Q.npy ]; then 
# Estimate covariance matrix and individual admixture proportions
echo "RUN"
date
time
python3 /home/kprovost/nas3/pcangsd/pcangsd.py \
-beagle $GL \
-admix -admix_save -e $k \
-inbreed 2 \
-selection -sites_save \
-o ${outname}.${spp}_PCAngsd.$k \
 -threads 32 > ${outname}.${spp}_pca.$k.log 2>&1
else
echo "ALREADY HERE1"
fi 
else
echo "ALREADY HERE2"
fi 
mv ./BEAGLE/${spp}/*selection* ./SELECTIONS/
mv ./BEAGLE/${spp}/*qopt* ./QOPTS/
mv ./BEAGLE/${spp}/*fopt* ./FOPTS/
mv ./BEAGLE/${spp}/*admix.F* ./FOPTS/
mv ./BEAGLE/${spp}/*admix.Q* ./QOPTS/
mv ./BEAGLE/${spp}/*cov* ./COV_INBREED/
mv ./BEAGLE/${spp}/*inbreed* ./COV_INBREED/
mv ./BEAGLE/${spp}/*sites* ./PCASITES/
mv ./BEAGLE/${spp}/*log* ./LOGS/
done
done
fi

done