#!/bin/bash
#PBS -l select=1:ncpus=32
#PBS -l walltime=5000:00:00
#PBS -N belflaNW_PCAngsd
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/BEAGLE/Vireo-bellii-NOWEIRD/FULL/

#Arguments:
## GL = genotype likehood file (Beagle format)

for GLu in *F.beagle; do 
#echo $GLu
gzip -f $GLu
done;

for GL in *.F.beagle.gz; do
echo "###################"
echo $GL
outname=${GL%.beagle.gz}
echo $outname
for k in {1..4}; do ## this does 2-5
echo $k
date
time
python /home/kprovost/nas3/pcangsd/pcangsd.py \
-beagle $GL \
-admix -admix_save -e $k \
-inbreed 2 \
-selection -sites_save \
-o ${outname}.${spp}_PCAngsd.$k \
 -threads 32 
done
done
