#!/bin/bash
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N sin_sfs3
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Geos_chrom/pseudochromosomesSHORT.fasta

##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo

## bam_list = list of BAM files
# sonlist=/home/kprovost/nas3/ANGSD_pipeline/SON_Cardinalis_sinuatus.indlist
# chilist=/home/kprovost/nas3/ANGSD_pipeline/CHI_Cardinalis_sinuatus.indlist

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

date
time


## now get the 2d sfs for each 
# time /home/kprovost/nas3/angsd/misc/realSFS \
# SON_CHI_Cardinalis_sinuatus.ml.1D.txt


echo "Prep for window analysis"

## failing because no ml 

# prepare the fst for easy window analysis etc
# ../misc/realSFS fst index pop1-sfs1.saf.idx pop2-sfs1.saf.idx -sfs pop1.pop2.ml.1D.txt -fstout here
time /home/kprovost/nas3/angsd/misc/realSFS fst index \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/SON_Cardinalis_sinuatus-sfs1.saf.idx \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/CHI_Cardinalis_sinuatus-sfs1.saf.idx \
-nSites 6365482 \
-sfs /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/MLFILES/SON_CHI_Cardinalis_sinuatus.ml.1D.txt \
-fstout /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SON_CHI_Cardinalis_sinuatus_FST 

echo "Get global estimate"

# get the global estimate
# ../misc/realSFS fst stats here.fst.idx 
# -> FST.Unweight:0.069395 Fst.Weight:0.042349
time /home/kprovost/nas3/angsd/misc/realSFS fst stats \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/FSTFILES/SON_CHI_Cardinalis_sinuatus_FST.fst.idx 

echo "Sliding Windows" 

# below is not tested that much, but seems to work
## this window seems too large
# ../misc/realSFS fst stats2 here.fst.idx -win 100000 -step 10000 >slidingwindow
time /home/kprovost/nas3/angsd/misc/realSFS  fst stats2 \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SON_CHI_Cardinalis_sinuatus_FST.fst.idx \
-win 100000 -step 10000 > /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SON_CHI_Cardinalis_sinuatus_FST_slidingwindow.fst