#!/bin/bash
#PBS -l select=1:ncpus=2:mem=64gb
#PBS -l walltime=99999:00:00
#PBS -N bru_sfs2
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Stur_chrom/pseudochromosomesSHORT.fasta

##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo

## bam_list = list of BAM files
sonlist=/home/kprovost/nas3/ANGSD_pipeline/SON_Campylorhynchus_brunneicapillus.indlist
chilist=/home/kprovost/nas3/ANGSD_pipeline/CHI_Campylorhynchus_brunneicapillus.indlist

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

date
time

# time /home/kprovost/nas3/angsd/angsd -GL 2 \
# -dosaf 1 \
# -fold 1 \
# -minInd 4 \
# -minMapQ 20 \
# -minQ 20 \
# -nThreads 16 \
# -ref $ref \
# -anc $ref \
# -bam $indlist \
# -out Campylorhynchus_brunneicapillus

## get the global sfs
echo "GLOBAL SFS"
time /home/kprovost/nas3/angsd/misc/realSFS -nSites 50000000 /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/Campylorhynchus_brunneicapillus-sfs1.saf.idx

## get the by population sfs 
echo 
echo "SON SFS"
/home/kprovost/nas3/angsd/angsd -b $sonlist \
-anc $ref \
-out SON_Campylorhynchus_brunneicapillus-sfs1 \
-dosaf 1 \
-gl 1

echo 
echo "CHI SFS"
/home/kprovost/nas3/angsd/angsd -b $chilist \
-anc $ref \
-out CHI_Campylorhynchus_brunneicapillus-sfs1 \
-dosaf 1 \
-gl 1

## now get the 2d sfs for each 
time /home/kprovost/nas3/angsd/misc/realSFS \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SON_Campylorhynchus_brunneicapillus-sfs1.saf.idx \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/CHI_Campylorhynchus_brunneicapillus-sfs1.saf.idx \
> SON_CHI_Campylorhynchus_brunneicapillus.ml
