#!/bin/bash
#PBS -l select=1:ncpus=32:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N bel-NOWEIRD_sfs1
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Corv_chrom/pseudochromosomesSHORT.fasta

## bam_list = list of BAM files
bamlist=/home/kprovost/nas3/ANGSD_pipeline/Vireo-bellii-NOWEIRD.bamlist

for i in /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/bellii/*.gz
do 
gunzip -f $i
done


cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

date
time

time /home/kprovost/nas3/angsd/angsd -GL 2 \
-dosaf 1 \
-fold 1 \
-minInd 4 \
-minMapQ 20 \
-minQ 20 \
-nThreads 16 \
-ref $ref \
-anc $ref \
-bam $bamlist \
-out Vireo-bellii-NOWEIRD-sfs1