#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=99999:00:00
#PBS -N sinBOTH_unfilter_analysis
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## first is output directory
output="/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/unfiltered_analysis"

## second is vcf string
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/
vcf1="sinuatus_unfiltered_CHI-SNP-only_no-missing-max25dp.recode.vcf"
#vcf1=sinuatus_unfiltered_CHI-SNP-only_alldata.recode.vcf
#vcf1=sinuatus_unfiltered_CHI-SNP-only-max25dp.recode.vcf

vcf2="sinuatus_unfiltered_SON-SNP-only_no-missing-max25dp.recode.vcf"
#vcf2="sinuatus_unfiltered_SON-SNP-only_alldata.recode.vcf"

if [ ! -f ${vcf1}.gz ]; then

echo "#######################"
echo Zip and Index $vcf1
echo "#######################"

echo Zip
#/home/kprovost/nas3/htslib/bgzip -c ${vcf1} > ${vcf1}.gz

echo Index
#/home/kprovost/nas3/bcftools/bcftools index ${vcf1}.gz

fi

if [ ! -f ${vcf2}.gz ]; then

echo "#######################"
echo Zip and Index $vcf2
echo "#######################"

echo Zip
#/home/kprovost/nas3/htslib/bgzip -c ${vcf2} > ${vcf2}.gz
echo Index
#/home/kprovost/nas3/bcftools/bcftools index ${vcf2}.gz

fi


vcf="sinuatus_unfiltered_BOTH-SNP-only_no-missing-max25dp.recode.vcf"
#vcf="sinuatus_unfiltered_BOTH-SNP-only_alldata.recode.vcf"

if [ ! -f ${vcf} ]; then

echo "#######################"
echo Merge VCF files
echo "#######################"

##/home/kprovost/nas3/bcftools/bcftools merge -O "v" -o $vcf ${vcf1}.gz ${vcf2}.gz 

fi 


## third is population information 
pops="/home/kprovost/nas3/populations_for_vcf_sinBOTH.txt"

## last is suffix (i.e., sinBOTH or whatever)
suffix="sinBOTHnomiss"

echo "#######################"
echo $vcf
echo "#######################"

module load R-3.4.1

Rscript /home/kprovost/nas3/vcf_pca.R $output $vcf $pops $suffix

## Rscript /Users/kprovost/Documents/Dissertation/CHAPTER2_GENOMES/ANALYSIS/vcf_pca.R "/Users/kprovost/Documents/Dissertation/CHAPTER2_GENOMES/ANALYSIS/" "/Users/kprovost/Documents/Dissertation/CHAPTER1_REVIEW/SLIM/runs/first_runs/slim-model3_isolation-1550691782/VCFS/model3_isolation-1550691782-1-overlaid.vcf" /Users/kprovost/Documents/Dissertation/CHAPTER1_REVIEW/SLIM/runs/first_runs/popcodes_model3_isolation-1550691782.txt "testvcf"
