#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=5000:00:00
#PBS -N lostruct_fus
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

## lostruct

## for flaviceps and bellii, some rows are empty. There are not enough markers in these windows? Trying with num pcs = 1, still fails. 
## for fusca, all of the rows are empty. not sure why. 

numPCS=2 ## default 2

logfile=fus.logfile

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/FOR_LOSTRUCT/

for vcffile in *vcf.gz; do 
echo $vcffile
## NOTE: lostruct needs headers to not have spaces in them
zcat $vcffile | sed -e "s/ //g" > ${vcffile%.vcf.gz}.nospace.vcf 
## bgzip
/home/kprovost/nas3/htslib/bgzip ${vcffile%.vcf.gz}.nospace.vcf 
## tabix
/home/kprovost/nas3/htslib/tabix ${vcffile%.vcf.gz}.nospace.vcf.gz
## convert to bcf
#/home/kprovost/nas3/bcftools/bcftools view -O b -o ${vcffile%.vcf.gz}.nospace.bcf ${vcffile%.vcf.gz}.nospace.vcf.gz
## then index 
#/home/kprovost/nas3/bcftools/bcftools index -f ${vcffile%.vcf.gz}.bcf
done;

## then load modules
module load R-3.6.3 
module load bcftools-1.10.2

if [ ! -d "working" ]; then mkdir working; fi
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/FOR_LOSTRUCT/

for file in *.nospace.vcf.gz; do
echo $file
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/FOR_LOSTRUCT/
cp ${file}* ./working
cd ./working
Rscript /home/kprovost/nas3/LOSTRUCT/run_lostruct.R -t bp -k $numPCS -s 100000 -i ./ > $logfile 2>&1
mv ./*.* /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/FOR_LOSTRUCT/
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/FOR_LOSTRUCT/
done
