#!/bin/bash
#PBS -l select=2:ncpus=64:mem=32gb
#PBS -l walltime=5000:00:00
#PBS -N BWA_alignment
#PBS -j oe
#PBS -m ae
#PBS -M lmoreira@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence

ref=~/nas3/Picoides_pubescens_reference_genome/Picoides_pubescens_ref-sorted.fa

date
time

module load bwa-0.7.15
module load fastqc-0.11.5
module load R-3.4.1
source activate stampy

for i in raw_reads/*_R1.fastq.gz; do
        read1=$i
        name=`echo $read1 | cut -d '/' -f2 | cut -d '_' -f1`
        read2ending="_R2.fastq.gz"
        read2=raw_reads/$name$read2ending
	header=`zcat $read1 | head -1`
	IFS=':' read -a header <<< "$header"
	INSTRUMENT=${header[0]}
	RUN_ID=${header[1]}
	FLOWCELL_BARCODE=${header[2]}
	LANE=${header[3]}
	ID=$FLOWCELL_BARCODE.$LANE
	PU=$FLOWCELL_BARCODE.$LANE.$name
	SM=$name
	PL=ILLUMINA
	LB=TrueSeq
        echo $name $read1 $read2 $ID $PU $SM $PL $LB
	
	echo
	echo "#######################"
	echo $name
	echo "#######################"

	echo
	echo
	echo Trimming adapters
	echo
	echo

	time java -jar /home/lmoreira/programs/Trimmomatic-0.36/trimmomatic-0.36.jar \
	PE $read1 $read2 \
	raw_reads/$name.forward_paired.fq.gz \
	raw_reads/$name.forward_unpaired.fq.gz \
	raw_reads/$name.reverse_paired.fq.gz \
	raw_reads/$name.reverse_unpaired.fq.gz \
	ILLUMINACLIP:/home/lmoreira/programs/Trimmomatic-0.36/adapters/TruSeq3-PE-2.fa:2:30:10:8:true

	echo
	echo	
	echo Quality assessment
	echo
	echo

	time fastqc raw_reads/$name.forward_paired.fq.gz
	time fastqc raw_reads/$name.reverse_paired.fq.gz

	echo
	echo	
	echo Running BWA alignment
	echo
	echo
	
	if [ ! -d "BAM_files/" ]; then mkdir BAM_files; fi 
	time bwa mem \
	-M \
	-t 28 \
	$ref \
	raw_reads/$name.forward_paired.fq.gz \
	raw_reads/$name.reverse_paired.fq.gz \
	> BAM_files/$name.sam

	echo	
	echo
	echo Converting SAM to sorted BAM
	echo
	echo	
	
	mkdir tmp
	time java -jar ~/programs/picard/picard.jar SortSam \
	INPUT=BAM_files/$name.sam \
	OUTPUT=BAM_files/$name.bam \
	SORT_ORDER=coordinate \
	TMP_DIR=`pwd`/tmp
	rm -r tmp/
	rm BAM_files/$name.sam

#       echo
#       echo
#       echo Running Stampy
#       echo
#       echo

#       time stampy -g Picoides_pubescens -h Picoides_pubscens \
#       --bamkeepgoodreads \
#       -M BAM_files/$name.bwa.bam \
#       -t64 \
#       --substitutionrate=0.025 \
#       -o BAM_files/$name.sam
#	rm BAM_files/$name.bwa.bam

#	mkdir tmp
#       time java -jar ~/programs/picard/picard.jar SortSam \
#       INPUT=BAM_files/$name.sam \
#       OUTPUT=BAM_files/$name.bwa.bam \
#       SORT_ORDER=coordinate \
#       TMP_DIR=`pwd`/tmp
#       rm -r tmp/
#       rm BAM_files/$name.sam

	echo
	echo
	echo Adding Read Group
	echo
	echo
	
	time java -jar ~/programs/picard/picard.jar AddOrReplaceReadGroups \
	I=BAM_files/$name.bam \
	O=BAM_files/$name.groups_added.bam \
	RGID=$ID \
	RGLB=$LB \
	RGPL=$PL \
	RGPU=$PU \
	RGSM=$SM
	rm BAM_files/$name.bam

	echo
	echo
	echo Deduplication
	echo
	echo
	
	time java -jar ~/programs/picard/picard.jar MarkDuplicates \
	TMP_DIR=tmp \
	I=BAM_files/$name.groups_added.bam \
	O=BAM_files/$name.dedup.bam \
	METRICS_FILE=Stats/$name.dedup.metrics.txt \
	REMOVE_DUPLICATES=false \
	MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1024 \
	TAGGING_POLICY=All
	rm -r tmp/
	rm BAM_files/$name.groups_added.bam

        echo
        echo
        echo Collecting alignment metrics
        echo
        echo

        if [ ! -d "Stats/" ]; then mkdir Stats; fi

        time java -jar ~/programs/picard/picard.jar CollectAlignmentSummaryMetrics \
        INPUT=BAM_files/$name.dedup.bam \
        OUTPUT=Stats/$name.alignment_metrics.txt \
        R=$ref \
        METRIC_ACCUMULATION_LEVEL=SAMPLE \
        METRIC_ACCUMULATION_LEVEL=READ_GROUP \

        echo
        echo
        echo Collect Insert Size Metrics
        echo
        echo

        time java -jar ~/programs/picard/picard.jar CollectInsertSizeMetrics \
        INPUT=BAM_files/$name.dedup.bam \
        OUTPUT=Stats/$name.insert_metrics.txt \
        HISTOGRAM_FILE=Stats/$name.insert_size_histogram.pdf

        echo
        echo
        echo Collect Coverage Metrics
        echo
        echo

        time java -jar ~/programs/picard/picard.jar CollectRawWgsMetrics \
        I=BAM_files/$name.dedup.bam \
        O=Stats/$name.raw_wgs_metrics.txt \
        R=$ref \
        INCLUDE_BQ_HISTOGRAM=true

	echo
	echo
	echo Indexing BAM
	echo
	echo
	
	time java -jar ~/programs/picard/picard.jar BuildBamIndex \
	I=BAM_files/$name.dedup.bam

	echo
	echo
        echo Running QUALIMAP
        echo
        echo

	time qualimap bamqc -nt 8 -bam BAM_files/$name.dedup.bam -outdir Stats/$name.QUALIMAP --java-mem-size=8G 

	echo
	echo "#######################"
	echo $name DONE!
	echo "#######################"
	echo
	echo

done

