#!/bin/bash
#PBS -l select=2:ncpus=64
#PBS -l walltime=5000:00:00
#PBS -N S1S2_mel4_BWA_align
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zonotrichia_albicollis_GCF_000385455.1_Zonotrichia_albicollis-1.0.1_genomic.fna
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Strunus_vulgaris_GCF_001447265.1_Sturnus_vulgaris-1.0_genomic.fna
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Geospiza_fortis_GCF_000277835.1_GeoFor_1.0_genomic.fna 


##References:
##Corvus -- Vireo bellii
##Parus -- Auriparus flaviceps
##Sturnus -- Toxostoma curvirostre, Toxostoma crissale, Campylorhynchus brunneicapillus, Polioptila melanura, Phainopepla nitens
##Zonotrichia -- Amphispiza bilineata, Pipilo fuscus
##Geospiza -- Cardinalis cardinalis, Cardinalis sinuatus

cd /home/kprovost/nas3/AMN_245109/sequences/melanura/single_bam_mel/

date
time

module load bwa-0.7.15
module load fastqc-0.11.5
module load R-3.4.1
	
ID="."
PU="..*"
SM="*"
PL=ILLUMINA
LB=TrueSeq
	
for name in AMN_245109_P002_W*_melanura.bam; do


		namei=${name%.bam}

		echo
		echo "#######################"
		echo $namei
		echo "#######################"


		#echo
		#echo
		#echo Adding Read Group
		#echo
		#echo

		#time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar AddOrReplaceReadGroups \
		#I=$namei \
		#O=$namei.groups_added.bam \
		#RGID=$ID \
		#RGLB=$LB \
		#RGPL=$PL \
		#RGPU=$PU \
		#RGSM=$SM
		
# 		echo
# 		echo
# 		echo Deduplication
# 		echo
# 		echo
# 	
# 		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar MarkDuplicates \
# 		TMP_DIR=tmp \
# 		I=$namei.groups_added.bam \
# 		O=$namei.dedup.bam \
# 		METRICS_FILE=$namei.dedup.metrics.txt \
# 		REMOVE_DUPLICATES=false \
# 		MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1024 \
# 		TAGGING_POLICY=All

		echo
		echo
		echo Collect Coverage Metrics ########
		echo
		echo

		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar CollectRawWgsMetrics \
		I=$namei.bam \
		O=$namei.raw_wgs_metrics.txt \
		R=$ref \
		INCLUDE_BQ_HISTOGRAM=true

		echo
		echo
		echo Indexing BAM
		echo
		echo
	
		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar BuildBamIndex \
		I=$namei.dedup.bam

# 		echo
# 		echo
# 		echo Validating BAM
# 		echo
# 		echo
# 
# 		time java -jar /home/kprovost/nas3/genomeresequencingFromLucas/picard.jar ValidateSamFile \
# 		I=$namei.dedup.bam \
# 		O=$namei.validate.txt \
# 		MODE=SUMMARY	
	
		#rm $namei.sam
		#rm $namei.bam

		echo
		echo
		echo Qualimap
		echo
		echo
		
		qualimap bamqc -nt 8 -bam $namei.dedup.bam -outdir $namei.QUALIMAP

		echo
		echo "#######################"
		echo $namei DONE!
		echo "#######################"
		echo
		echo
done;