#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=999999:00:00
#PBS -N plot_dxy_rscript
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/DXY/

module load R-3.4.1

#mkdir DONE

#Rscript /home/kprovost/nas3/ANGSD_pipeline/plotDXY_huxley.R

#mv *_persite.txt ./DONE

for i in *_persite.txt.gz; do
gunzip -f $i
done

Rscript /home/kprovost/nas3/ANGSD_pipeline/plotDXY_huxley.R

#mv *_persite.txt ./DONE
