#!/bin/bash
#PBS -l select=1:ncpus=2
#PBS -l walltime=99999:00:00
#PBS -N belSON_S4_combinegvcf
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Corvus_brachyrhynchus_GCF_000691975.1_ASM69197v1_genomic.fna
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Geospiza_fortis_GCF_000277835.1_GeoFor_1.0_genomic.fna
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Parus_major_GCF_001522545.2_Parus_major1.1_genomic.fna
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Strunus_vulgaris_GCF_001447265.1_Sturnus_vulgaris-1.0_genomic.fna
#ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zonotrichia_albicollis_GCF_000385455.1_Zonotrichia_albicollis-1.0.1_genomic.fna

##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Melozone

## NOTE: redid this for the renamed VCF files, this time also split into sonoran and chihuahuan populations

## or whatever 
cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/



echo
echo
echo Combine GVCFs
echo
echo


## CHANGE AS NEEDED
time java -Djava.io.tmpdir=/home/kprovost/nas3/tmp/ -jar /home/kprovost/nas3/genomeresequencingFromLucas/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar \
-T GenotypeGVCFs \
-R $ref \
--variant /vz-nas1-active/ProcessedGenomicReads/AMN_245111/Plate2/bellii/December_Rerun/BAM_files/not_merged/vcf_files/AMN_245111_P002_WA06_bellii.raw.g.vcf \
--variant /vz-nas1-active/ProcessedGenomicReads/AMN_245111/Plate2/bellii/December_Rerun/BAM_files/not_merged/vcf_files/AMN_245111_P002_WC01_bellii.raw.g.vcf \
--variant /vz-nas1-active/ProcessedGenomicReads/AMN_245111/Plate2/bellii/December_Rerun/BAM_files/not_merged/vcf_files/AMN_245111_P002_WD07_bellii.raw.g.vcf \
--variant /vz-nas1-active/ProcessedGenomicReads/AMN_245111/Plate2/bellii/December_Rerun/BAM_files/not_merged/vcf_files/AMN_245111_P002_WD11_bellii.raw.g.vcf \
--variant /vz-nas1-active/ProcessedGenomicReads/AMN_245111/Plate2/bellii/December_Rerun/BAM_files/not_merged/vcf_files/AMN_245111_P002_WF03_bellii.raw.g.vcf \
-o allsamples_111_bellii_SON.raw.vcf
#-nt 64
##### nt not there originally, didn't have slash before
#30 oct 2018: removed -nt to see if would fix the memory issues

