#!/bin/bash
#PBS -l select=1:ncpus=32
#PBS -l walltime=5000:00:00
#PBS -N belNW_SONtaj1
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Corv_chrom/pseudochromosomesSHORT.fasta

## bam_list = list of BAM files
bamlist=/home/kprovost/nas3/ANGSD_pipeline/SON_Vireo_bellii-NOWEIRD.indlist

# for i in /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/bellii/*gz; do
# echo $i; gunzip $i; done

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel-NW/

date
time

time /home/kprovost/nas3/angsd/angsd -bam $bamlist -doSaf 1 -anc $ref -GL 1 -P 24 -out Vireo-bellii-NOWEIRD-SON-taj1

time /home/kprovost/nas3/angsd/misc/realSFS \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/SAFS/bel-NW/Vireo-bellii-NOWEIRD-SON-taj1.saf.idx \
> Vireo-bellii-NOWEIRD-SON-taj.sfs

time /home/kprovost/nas3/angsd/angsd -GL 2 -bam $bamlist -doThetas 1 -doSaf 1 -pest Vireo-bellii-NOWEIRD-SON-taj.sfs -anc $ref -out Vireo-bellii-NOWEIRD-SON-taj2 

#Estimate for every Chromosome/scaffold
time /home/kprovost/nas3/angsd/misc/thetaStat do_stat \
Vireo-bellii-NOWEIRD-SON-taj2.thetas.idx

#Do a sliding window analysis based on the output from the make_bed command.
time /home/kprovost/nas3/angsd/misc/thetaStat do_stat \
Vireo-bellii-NOWEIRD-SON-taj2.thetas.idx \
-win 100000 \
-step 10000  \
-outnames Vireo-bellii-NOWEIRD-SON-taj2.thetasWindow.gz