#!/bin/bash
#PBS -l select=1:ncpus=4
#PBS -l walltime=5000:00:00
#PBS -N bil_taj1
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

#Arguments:
## ref=reference sequence
ref=/home/kprovost/nas3/genomeresequencingFromLucas/Zono_chrom/pseudochromosomesSHORT.fasta

##References:
##Corvus -- Vireo
##Geospiza -- Cardinalis
##Parus -- Auriparus
##Sturnus -- Toxostoma, Campylorhynchus, Polioptila, Phainopepla
##Zonotrichia -- Amphispiza, Pipilo

## bam_list = list of BAM files
# sonlist=/home/kprovost/nas3/ANGSD_pipeline/SON_Vireo_bellii.indlist
# chilist=/home/kprovost/nas3/ANGSD_pipeline/CHI_Vireo_bellii.indlist
bamlist=/home/kprovost/nas3/ANGSD_pipeline/Amphispiza-bilineata.bamlist

cd /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/

date
time

time /home/kprovost/nas3/angsd/angsd -bam $bamlist -doSaf 1 -anc $ref -GL 1 -P 24 -out Amphispiza-bilineata-taj1

time /home/kprovost/nas3/angsd/misc/realSFS \
/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/Amphispiza-bilineata-taj1.saf.idx \
> Amphispiza-bilineata-taj.sfs

time /home/kprovost/nas3/angsd/angsd -GL 2 -bam $bamlist -doThetas 1 -doSaf 1 -pest Amphispiza-bilineata-taj.sfs -anc $ref -out Amphispiza-bilineata-taj2 

#Estimate for every Chromosome/scaffold
time /home/kprovost/nas3/angsd/misc/thetaStat do_stat \
Amphispiza-bilineata-taj2.thetas.idx

#Do a sliding window analysis based on the output from the make_bed command.
time /home/kprovost/nas3/angsd/misc/thetaStat do_stat \
Amphispiza-bilineata-taj2.thetas.idx \
-win 100000 \
-step 10000  \
-outnames Amphispiza-bilineata-taj2.thetasWindow.gz